### ISSUE TITLE
some suggestions about teal generated code

### ISSUE THREAD

**Issue by virusdefender** [teal-language/tl#109]
`main.tl`

```
global type1 = record
end

local type_2 = record
end

local func1 = function()
end

local func2 = function()
    local a = 100
    local b = a
end

-- multi
-- multi
-- multi
-- multi
-- line
-- comment
local c = 100
```

`demo.generated.lua`

```lua
 type1 = {}


local type_2 = {}


local func1 = function()
 end

local func2 = function()
   local a = 100
   local b = a
end







local c = 100
```

I'm using luacheck to lint generated lua code to find issue in tl files and there are some warnings, to make linter happy, `tl check` can generate more readable and strict code.

 - ` type1 = {}` there is one more space before `type1` if the variable is `global`
 - all generated multi line code use three whitespace instead of four whitespace

```
local func2 = function()
___local a = 100
___local b = a
end
```

 - there is one more space before `end` if the function is empty

```
local func1 = function()
 end
```
 - maybe there is no need to generate `type1` and `type2` variables into lua code?
 - comments in tl code are replaced to empty lines in lua code, may be it should be replaced to empty string

**Comment by hishamhm** [comment]
The generated Lua code is mostly for machine consumption. Nowadays it is mostly 1-to-1 with the Teal code, but there are no future guarantees on that. 

> * type1 = {} there is one more space before type1 if the variable is global

> * there is one more space before end if the function is empty

At one point I plan to reuse that code to produce a Teal formatter, so I will look into fixing those indentation mistakes...

> * all generated multi line code use three whitespace instead of four whitespace

...but otherwise, right now there's no plans to preserve the input file's indentation style etc.

> * maybe there is no need to generate type1 and type2 variables into lua code?

This is a valid point, and this was raised before, but right now records are reified as tables, because they allow for a "prototype-based" style of module declaration that is useful. So generating them doesn't hurt, and actually helps. In the future I might make some more use of those tables too for identifying types at runtime (a sort of RTTI).

> * comments in tl code are replaced to empty lines in lua code, may be it should be replaced to empty string

Those blank lines are added on purpose, to make the line numbers in the output code (and error backtraces) match the ones from the input `.tl` file (there's nothing like sourcemaps at the Lua VM level to fix backtraces).

I will keep this issue open because of the indentation mistakes above that need to be fixed, but this is low-priority at this stage. Still, thank you for the input!
