### ISSUE TITLE
Array and map variables accept larger types

### ISSUE THREAD

**Issue by SvenMarcus** [teal-language/tl#117]
I have found that arrays and maps allow for entries that shouldn't be there:

Array:
```lua
local scripts: {string} = {
    "multilayer",
    "fighter-spawn",
    "single-unit-retreat",
    invalid = 0
}
```

Map:
```lua
local map_test: {string:function} = {
    a = function() end,
    b = function() end,
    "hello"
}
```

**Comment by hishamhm** [comment]
This happens because of current lax type compatibility rules. Suppose you have a function like this:

```lua
-- this is a generic function that works for arrays of any type
-- but the fact that it is generic doesn't matter
local function has_children<T>(xs: {T}) do
   return #xs > 0
end
```

and you have an object that does contain both a "hash part" an an "array part", in Lua terms:

```lua
local object = {
   child1,
   child2,
   child3,
   x = 12,
   y = 13,
   name = "myobject",
}

local h = has_children(parent)
```

If an array type accepts only pure arrays, the above doesn't work. 

At first you might look at the above and say "well, then make that invalid and demand an explicit cast", but this is a super common pattern in Lua (think of all the `table` functions in the standard library which accept arrays and are often used with hybrid objects). A similar situation happens with return values.

Having said that, maybe these rules could be made stricter for assignment or for table literals specifically, but then it can get really confusing if some things work in some places but not in others.

I'll think some more about it. Thanks for the feedback!

**Comment by hishamhm** [comment]
(I tweaked the title to make the topic more descriptive to what is really going on)

**Comment by hishamhm** [comment]
@SvenMarcus this is finally fixed! the fix is merged in `master` and should feature in the next release!
