### ISSUE TITLE
`typealias` construct?

### ISSUE THREAD

**Issue by pdesaulniers** [teal-language/tl#137]
Teal supports `functiontype` to avoid longwinded function type declarations. In that case, why not add a generic construct for creating type aliases of any kind? This could be useful with union types:
```lua
local Something = typealias(number | string | SuperLongTypeName)
local x: Something = 0
```

**Comment by hishamhm** [comment]
That's a good idea, and if it accepts a general `type` (as in the grammar.md rule `type`), then it even renders `functiontype` redundant since it could be instead a `typealias(function() ...)` instead. I wouldn't mind replacing it with something more general, never liked the name `functiontype` a lot.

Not sure I like the parentheses in the syntax because it makes it look like a function call, but since types can be parenthesized at the top level, I guess even without them something like `typealias (number | string | SuperLongTypeName)` would be valid anyway.

**Comment by pdesaulniers** [comment]
I'm satisfied with https://github.com/teal-language/tl/pull/194. I think https://github.com/teal-language/tl/pull/159 and
https://github.com/teal-language/tl/issues/170 can be closed as well.
