### ISSUE TITLE
tl.lua:53131: attempt to index local 'u1' (a nil value)

### ISSUE THREAD

**Issue by Duckxz** [teal-language/tl#141]
https://hastebin.com/dawodasuqa.rb is the code

stacktrace:

```/usr/bin/lua5.1: /usr/share/lua/5.1/tl.lua:5131: attempt to index local 'u1' (a nil value)
stack traceback:
	/usr/share/lua/5.1/tl.lua:5131: in function 'subtract_types'
	/usr/share/lua/5.1/tl.lua:5213: in function 'facts_not'
	/usr/share/lua/5.1/tl.lua:5487: in function 'before'
	/usr/share/lua/5.1/tl.lua:2072: in function 'visit_before'
	/usr/share/lua/5.1/tl.lua:2161: in function 'recurse_node'
	/usr/share/lua/5.1/tl.lua:2196: in function 'recurse_node'
	/usr/share/lua/5.1/tl.lua:2171: in function 'recurse_node'
	/usr/share/lua/5.1/tl.lua:2251: in function 'recurse_node'
	/usr/share/lua/5.1/tl.lua:2171: in function 'recurse_node'
	/usr/share/lua/5.1/tl.lua:6148: in function 'type_check'
	/usr/share/lua/5.1/tl.lua:6241: in function 'process'
	/usr/lib/luarocks/rocks-5.1/tl/0.5.2-1/bin/tl:210: in main chunk
```

**Comment by hishamhm** [comment]
@Duckxz Thanks for reporting the issue! I'm getting this when I try to run that code:
```
========================================
20 errors:
bla.tl:3:1: module not found: './love'
bla.tl:4:1: module not found: './aabb'
bla.tl:5:1: module not found: './math'
bla.tl:6:1: module not found: './graphics'
bla.tl:7:1: module not found: './entity'
bla.tl:8:1: module not found: './map'
bla.tl:11:21: unknown type Entity
bla.tl:12:9: unknown type Map
bla.tl:14:42: unknown type Entity
bla.tl:17:27: unknown type Map
bla.tl:33:3: excess return values, expected 0 got 1
bla.tl:44:37: unknown type Entity
bla.tl:45:18: unknown type Entity
bla.tl:48:17: cannot index something that is not a record: Entity (an unknown type)
bla.tl:63:5: cannot index something that is not a record: Entity (an unknown type)
bla.tl:67:29: unknown type Map
bla.tl:68:17: unknown type Map
bla.tl:79:5: unknown variable: love
bla.tl:80:5: cannot index something that is not a record: Entity (an unknown type)
bla.tl:81:5: unknown variable: love
```
which means I can't reproduce the crash without the other modules. Could you zip them together and make them available?

**Comment by Duckxz** [comment]
right sorry, here it is
https://send.firefox.com/download/47db8829a366e925/#nbNLnqCF6mdHDEtFDCSyyA

**Comment by hishamhm** [comment]
@Duckxz Thank you for the files, they were really useful! I found and fixed that particular issue.

Looking at your files (impressive work typing the Love2D library!!), I hit two other issues which you will hit soon:

* one is that `thread` is now a primitive type name, and that clashes with your use of `thread` as a nested type name (I had to change it explicitly to `love.thread` to avoid the conflict) — @euclidianAce, I think this is an issue a lot of people may run into, since `thread` seems like a common word for user module names... what do you think about renaming the primitive type to `coroutine` (even though the I know the Lua type is called "thread") — since `coroutine` is a standard library module (like `string`) I think that's highly unlikely to cause conflicts with user libraries.

* another issue is that you are declaring union types between different kinds of userdata (e.g. `Image | Source`), which Teal doesn't support yet. From my local tests of Love2D, I see that these userdata have different metatables, which we could eventually use to identify them, but we still need to figure out how to declare these types (see #133) and how to declare the mapping of these metatables.

**Comment by euclidianAce** [comment]
@hishamhm I'll preface this with the fact that I wouldn't mind it changing and it's not a huge deal since it seems like coroutines are one of the least used things in Lua.
But, not to sound abrasive, I am of the opinion that:
 - To me, a thread in a Lua context is a coroutine, and I'd be personally fine using a namespaced type like `love.thread` to reference a different type of thread.
 - A primitive type name not lining up like that isn't great
 - Something that differs from what Lua considers a thread should be named accordingly (although there probably isn't a better name than thread, which is why I'm okay with changing it).

But I do concede that this is probably not the majority opinion, and with coroutines only being created through coroutine functions, we almost never will actually have to annotate a variable with the type of `thread` due to type inference. I'm 100% fine with changing it if you'd like.

**Comment by Duckxz** [comment]
Thank you for fixing it!

and yeah i was going to change most multi type arguments to instances of `any` until teal is able to discriminate custom types. i also didn't know about .d.tl yet so i named it Love because it was creating an empty table overriding the love namespace

**Comment by pdesaulniers** [comment]
@Duckxz By the way, feel free to contribute your Love2D declarations to https://github.com/teal-language/teal-types, even if they're not finished! I'm sure a lot of users would be interested in these.
