### ISSUE TITLE
how to `load` tl inside lua file?

### ISSUE THREAD

**Issue by darrenjennings** [teal-language/tl#169]
How to load a tl string in lua file?

```lua
-- test.lua
local tl = require('tl')
tl.loader()

local program, err = load('local a: string = "hey";print(a);')
print(program, err)
```

```
$ lua test.lua
nil	[string "local a: string = "hey";print(a);"]:1: unexpected symbol near ':'
```

**Comment by hishamhm** [comment]
Ohh, good catch, I guess the `tl` module needs to add a `tl.load()` function (for a second I thought of monkey-patching `load()` but that function a chunked reading mode and people generally frown upon monkey-patching standard Lua functions — `require()` provides an extensibility model, so that's different).

**Comment by hishamhm** [comment]
`master` now has a `tl.load` function :grin: (you can install the latest master with `luarocks install --dev tl`)
