### ISSUE TITLE
Introduce `newtype`

### ISSUE THREAD

**Issue by mspielberg** [teal-language/tl#170]
When working with complex type like `{number:{number:Projectile}}` the repetition gets very tedious to write, difficult to read, and impossible to maintain if the type ever changes. I'd like to create a name like "ProjectileMap," but currently the only way to do this would be to introduce a single field record:
```lua
local ProjectileMap = record
  value: {number:{number:Projectile}}
end
```
This is bad for usability, since now `value` has to appear everywhere, and bad for runtime performance since an extra table dereference is required with every use.

I would like a way to tell Teal to use the most straightforward runtime representation and continue to allow the same syntax as using the original map type. My suggestion is to borrow from Haskell and call this `newtype`:
```lua
local ProjectileMap = newtype {number:{number:Projectile}}
```

Note that this is distinct from #137 because I actually want a new type to be created and tracked, and confusion between two types with identical runtime representation to be caught at compile-time:

```lua
local ErrorTranslations = typealias({number:string})
local HttpStatus = typealias({number:string})
```
With type aliases, it would be possible to mix and match variables declared with these types, because an alias is just that, and each variable would have the same underlying type.

With `newtype`, these would be separate types that could not be intermingled, just as `record` does.

**Comment by pdesaulniers** [comment]
> With type aliases, it would be possible to mix and match variables declared with these types, because an alias is just that, and each variable would have the same underlying type.

In its current implementation (see https://github.com/teal-language/tl/pull/159), I believe `typealias` behaves like your `newtype` proposal. For instance, this throws an error:

```lua
local ErrorTranslations = typealias {number:string}
local HttpStatus = typealias {number:string}

local translations: ErrorTranslations = {
   [404] = "not found"
}

local status: HttpStatus = translations
```

```
========================================
1 error:
test.tl:8:7: in local declaration: status: ErrorTranslations is not a HttpStatus
```

**Comment by hishamhm** [comment]
I was thinking about this distinction just yesterday, and in fact it's one of the reasons I've been holding back on merging that PR.

One of my general design goals in Teal was to have the type system lean towards a nominal type system (types of different names are different types) than a structural type system (types of different shapes are different types). For this reason, whenever two named types are compared, they are compared by name (with the additional complexities imposed by aliasing and the Lua legacy, such as the fact that the same types may have different qualified names when required from different modules).

One main difference from a purely nominal system, though, is that type constructors (a.k.a... tables!) are not named. For this reason, there is a structural comparison that goes on between named and unnamed types.

For this reason, what is implemented in #137 is neither a transparent alias like a C typedef, or a Haskell-like newtype (if my memory of Haskell is correct: you can't pass a list without a named constructor to an argument that expects a type declared as a newtype of that list, right?)

The question then becomes what to name it!

**Comment by luauser32167** [comment]
> One main difference from a purely nominal system, though, is that type constructors (a.k.a... tables!) are not named. For this reason, there is a structural comparison that goes on between named and unnamed types.

Maybe "named type constructors" could be added similar to struct literals in C, Rust, Go?
```
local Point = record
    x: number
    y: number
end

local p1 = Point{}
local p2 = Point{x=1}
local p3 = Point{x = 2, y =3}
```

**Comment by hishamhm** [comment]
> Maybe "named type constructors" could be added similar to struct literals in C, Rust, Go?

That's a reasonable option which sound okayish for records (even though for a Lua programmer that looks like a function call so it's a bit misleading), but when you consider all other named types like functions and enums, it starts to be a cumbersome departure from what a Lua programmer is used to — think enums: I wouldn't like to type `Direction "north"` every time instead of `"north"`.

I think that construction makes sense for invoking a constructor given a language-native OOP model, but forcing the use of named type constructors in general sounds a little excessive from a user standpoint (even thought it would make things easier for the language designer!)

**Comment by hishamhm** [comment]
> if my memory of Haskell is correct: you can't pass a list without a named constructor to an argument that expects a type declared as a newtype of that list, right?

And yes, I just got in front of the computer and tested this in Haskell:

```haskell
newtype StringList = StringList [String]

getFirst :: StringList -> String
getFirst (StringList sl) = head sl -- you need to "unwrap the argument" to use the list

main = print (getFirst (StringList ["hello"]))  -- you need to "wrap the list" to pass the argument
```

**Comment by hishamhm** [comment]
In Teal with #137, the above becomes:

```
local StringList = typealias {string}

local function get_first(sl: StringList): string
   return sl[1] -- no need to unwrap
end

print(get_first({"hello"})) -- no need to wrap
```

but as @pdesaulniers said, if you have two named types, you can't mix them up. 

Note, however, that if you go out of your way to lose type information, you can still do this:

```
local StringList = typealias {string}
local AnotherList = typealias {string}

local function get_first(sl: StringList): string
   -- local a: AnotherList = sl -- <= doesn't work, as expected!
   local raw: {string} = sl -- drop type information
   local a: AnotherList = raw -- now this assignment works
   return sl[1]
end

print(get_first({"hello"}))
```

Does that sound like a reasonable compromise between safety, usability and Lua familiarity?

**Comment by pdesaulniers** [comment]
Personally, I think the current behavior is fine. At least, it seems compatible with how the language works so far, and I don't see how it could go wrong in practice. Of course, I'd be happy to be proven wrong with a scary example :)

Interestingly, we're being stricter than TypeScript, which implements "true" type aliases:
```ts
type StringList = [string];
type AnotherList = [string];

function getFirst(sl: StringList): string {
	let ab: AnotherList = sl; // this is allowed!
	let raw: [string] = sl; // this is allowed too!
	return sl[0];
}

console.log(getFirst(["hello"]));
```

With that said, now that I'm aware of `newtype`, I think it's a better name for the feature than `typealias`.

**Comment by mspielberg** [comment]
I’m happy with the semantics of the current PR. Automatic promotion from unnamed structural type to nominal type is consistent with how records already behave. I think the balance of safety and ease of interior with standard Lua (structural) APIs is well done.

Note that I’m coming from Scala, which offers both newtype via compile-time optimization of single field records that carry an annotation enabling the optimization:

```scala
case class StringList(value: List[String]) extends AnyVal
```

and true aliasing:

```scala
type StringList = List[String]
```

**Comment by hishamhm** [comment]
I am slightly concerned that reusing keywords from other languages with different semantics will continue to cause confusing (just like `typealias` isn't a true type alias as seen in languages that have that keyword, `newtype` wouldn't be a Haskell-like newtype).

One option that has been floating in my mind is a more extensive syntactical change: `local type` (and by extension `global type`), like this:

```
local type Point = record
   x: number
   y: number
end

local type Callback = function(string):string

local type Primitives = number | string | boolean

local type HasNested = record
   type Nested = record -- not sure about this "type" here but at first glance it sounds right
   end
   f: Nested
end

local type Sides = enum
   "left"
   "right"
end
```

This might help making the distinctions between types and other values clearer for the user.

It would also make the language more consistent, because right now a `local` declaration that assigns a type is pretty much special compared to other local variable declarations: you cannot do multiple assignment, and all types are auto-`<const>`.

**Comment by pdesaulniers** [comment]
One thing about this that comes to my mind: 

Right now, records are a type, but they're also a table instance. So, perhaps calling it just a "type" is a bit misleading. For instance, this would be valid:
```lua
local type Duck = record
end

function Duck.quack()
    print("quack!🦆")
end

Duck.quack()
```

but this would be invalid:
```lua
local type Duck = {string:function}

Duck["quack"] = function()
	print("quack!🦆")
end

Duck["quack"]()
```

So, I think records would ned to be changed so that they are just a 'plain' type, and not a table combined with a type.

**Comment by mspielberg** [comment]
> I am slightly concerned that reusing keywords from other languages with different semantics will continue to cause confusion (just like `typealias` isn't a true type alias as seen in languages that have that keyword, `newtype` wouldn't be a Haskell-like newtype).

Haskell [has 3 keywords](https://www.reddit.com/r/haskell/comments/6xri4d/whats_the_difference_between_newtype_type_and_data/) for creating new types, `data`, `newtype`, and `type`:

`data` &mdash; multiple named constructors allowed, each with any number of contained fields. Very similar to Rust's enums. Runtime representation carries a tag to identity the variant. Must be destructured by pattern matching on the constructor name to select the variant.

`newtype` &mdash; like data, but only 1 type constructor variant is allowed, which must have exactly 1 field. At runtime, the type is optimized away and the representation is exactly that of the underlying type. Uses pattern matching on the constructor name to maintain the parallel with `data`.

`type` &mdash; defines a true synonym/alias for the underlying type, which can be used interchangeably with the underlying type.

So if the concern is potential confusion for people familiar with Haskell, `type` is actually *worse* than `newtype`, and `newtype` is the closest equivalent. I wouldn't be concerned about the difference in use-site syntax. The closest equivalent for a Teal `record` would be Haskell's `data`, and records don't use the type name at use sites either.

> One option that has been floating in my mind is a more extensive syntactical change: `local type` (and by extension `global type`), like this:

I'm in favor of this syntactic change even without any semantic changes. `local TypeName = record ... end` looks quite bizarre as someone coming from Lua.

> Right now, records are a type, but they're also a table instance.

I wasn't aware of it, and now that I am, that is so weird! Is it documented anywhere?

**Comment by pdesaulniers** [comment]
> I wasn't aware of it, and now that I am, that is so weird! Is it documented anywhere?

You can see this in action in the Point example from the 'Records' section: https://github.com/teal-language/tl/blob/master/docs/tutorial.md#records

It looks something like:
```lua
local Point = record
   x: number
   y: number
end

-- we add a function inside the Point table
function Point.new(x: number, y: number): Point
   local self: Point = setmetatable({}, { __index = Point })
   self.x = x or 0
   self.y = y or 0
   return self
end
```

Then, we may call `Point.new(1, 2)` to create a new point.

**Comment by mspielberg** [comment]
On a second look, I guess this is implied by the ability to add "methods" to record types, and the ability to return the record type from a module. But it's still far from clear. What is the type of the record type? `any`? The record type itself? Does `Point` have `x` and `y` members, i.e. does every record type have "class" properties exactly matching its set of "instance" properties?

**Comment by hishamhm** [comment]
> So if the concern is potential confusion for people familiar with Haskell

I don't think people will look at the word `type` and immediatelly think "Haskell", but if it's called `newtype` (a very Haskell-specific term) then _I_ would think "Haskell". :)

> On a second look, I guess this is implied by the ability to add "methods" to record types, and the ability to return the record type from a module. But it's still far from clear.

Yes, it _is_ far from clear. This behavior was really a side-effect of this "prototype-based" nature of object-like and module table constructions in Lua.

> What is the type of the record type? any? The record type itself?

This is not exposed to the language as a first-class type (because hey, let's get the basics right first before going higher-order, shall we? :) ), but type definitions have an internal type (called `typetype` :) ) and specifically for records because of the constructs above, a `typetype` for a `record` R _is-a_ R.

> Does Point have x and y members, i.e. does every record type have "class" properties exactly matching its set of "instance" properties?

Currently, yes.

**Comment by hishamhm** [comment]
Also, I have noticed that the tutorial is currently lying! It says:

> This, however, won't work:
>
>> local p1 = { x = 100, y = 100 }
>> local p2: Point = p1 -- Error!

But in fact that does work! (And it's the reason why one no longer needs to write `as METATABLE` when declaring a metatable for `setmetatable`.) Need to change that example to create two structurally-identical named records.

**Comment by euclidianAce** [comment]
I think I'll throw my hat in the ring here coming from a Lua and C background. I'm personally for the `local type foo` construct. Since I've recently been using the 5.4rc, I had an idea that Teal could introduce it's own attributes and have something like 
```
local foo <type> = record
   --[[ ... ]]
end
```
This fits with the idea of types being auto-const since in 5.4 every local with an attribute is const. And once 5.4 rolls around, `<type>` could just get compiled to `<const>`. The main problem is that it wouldn't really allow for nested types since attributes are only for local declarations.
```
local hasNested <type> = record
   
   Nested1 = record end         -- maybe just allow this?
   Nested2 <type> = record end  -- attributes look wrong without a 'local'

   type Nested3 = record end    -- similar syntax to tagged records though
end
```
Although with types being auto-const, does that apply to nested types too? And const in the sense of compile-time checking for assignment, not runtime? So table entries could theoretically be const to the Teal compiler?

Just some food for thought.

**Comment by hishamhm** [comment]
> Although with types being auto-const, does that apply to nested types too? And const in the sense of compile-time checking for assignment, not runtime? 

Yes, in the sense of compile-time checking. The compiler does not let you assign to a variable of type `typetype` and produces an error saying `cannot reassign a type`.

But of course, you could pass the table to a Lua module which is oblivious to the compile-time checks and it could modify the nested values and mess things up.

We could in theory output `<const>` for the non-nested types at runtime for Lua 5.4, but that wouldn't gain us anything, since all checks for Teal locals already happened at compile time, and local variables are not visible to other modules, so other Lua modules can't touch these variables (keeping in mind that `<const>` applies to variables and not values).

Note also that Lua 5.4 does not have `<const>` for globals but Teal does. Again, Teal modules will respect this at compile time, but as soon as Lua modules are called, all bets are off.

**Comment by hishamhm** [comment]
We ended up implementing [this](https://github.com/teal-language/tl/issues/170#issuecomment-644169547) in Teal 0.8, so I think now this issue can be closed!
