### ISSUE TITLE
add generated output as available tl lib method

### ISSUE THREAD

**Issue by darrenjennings** [teal-language/tl#171]
It appears that tl can only process files, via `process`. It would also be nice if the cli commands of `gen` and `run` were available at the library level. I created a new method `tl.process_str`, by refactoring out the file io of `process`. Let me know if this sounds good, open to naming and function signatures. Right now it's:

```lua
tl.process(filename, env, result, preload_modules)
-- new method:
tl.process_str(input, env, result, preload_modules, is_lua, filename)
```

```lua
-- playground.lua
local tl = require('tl')

local code = [[
local message:string = "hello"
]]

local result = tl.process_str(code)
print(tl.pretty_print_ast(result.ast))
```

Maybe there be a function `tl.gen(input)` that returns the pretty printed string for you?

Background: this is helpful for the teal browser "playground"

**Comment by hishamhm** [comment]
Yes, both `tl.process_string` (with "string" fully spelled out maybe?) and `tl.gen` sound good!

I haven't put a lot of thought/effort in the `tl` library API, but since we're in 0.x days anyway, better to have _something_ out there, even if it grows organically according to the needs the arise, and clean it up for 1.0 in the distant future. :)
