### ISSUE TITLE
Forward declare a function on a module

### ISSUE THREAD

**Issue by Ruin0x11** [teal-language/tl#197]
Is it possible to forward declare a function on a module? This syntax works for plain values:

```lua
local get_working_directory: function(): string
```

But this results in a syntax error.

```lua
fs.get_working_directory: function(): string
```

The problem comes when I have to define a function with a circular dependency.

```lua
fs.get_working_directory: function(): string

function fs.to_relative(filepath: string): string
   filepath = fs.normalize(filepath)
   filepath = string.strip_prefix(filepath, fs.get_working_directory() .. "/")
   return filepath
end

local function wrap(cb: function(string, ...: any)): function(string, ...: any):(any...)
   return function(path: string, ...: any):(any...)
      return cb(fs.to_relative(path), ...)
   end
end

if is_love then
   fs.get_working_directory = function() return "directory" end
else
   fs.get_working_directory = love.filesystem.getWorkingDirectory
   fs.write = wrap(love.filesystem.write)
   fs.read = wrap(love.filesystem.read)
end
```

Is the recommended solution to change the organization of the code to prevent this?

**Comment by Ruin0x11** [comment]
Also, is there a reason the syntax for function declaration does not typecheck depending on the syntax used?

As far as I understand, these two ways of declaring a function are functionally equivalent.

```lua
local module = {}

function module.fn1(): boolean
    return true
end

module.fn2 = function(): boolean
   return true
end
```

But in `tl` only the first one typechecks. The second gives an error that `fn2` is an invalid key.

**Comment by euclidianAce** [comment]
This is part of the "record-extesion" (name?) feature. Since it can be annoying to have to forward declare things, Teal allows us to insert function definitions into a table/record with the
```
function foo.bar() end
```
syntax. But explicitly defining `foo.bar = ...` is treated the same as accessing a non existent entry in a table/record, so Teal complains (to help catch misspellings and what not, if you meant `foo.baz` or used it in something other than an assignment, Teal is right to complain here). In Lua those two function definitions are the same, but in Teal they have subtly different semantics.

To forward declare something in a table, you can do it when you initialize the table.
```
local module = {
   fn1: function(): boolean = nil
}
```
Teal will then see that `fn1` is a valid entry in the table, and let you assign to it with `module.fn1 = ...`

See the `Point` example in the tutorial [here](https://github.com/teal-language/tl/blob/master/docs/tutorial.md#records)

**Comment by Ruin0x11** [comment]
Ok, thanks.
