### ISSUE TITLE
Error building project with multiple files

### ISSUE THREAD

**Issue by Grinshpon** [teal-language/tl#229]
I have a basic project (using Love2d) set up like so:

```
src/
| main.tl
| setup.tl
| input.tl
```

where `main.tl` contains lines that call `require "setup"` and `require "input"`.

And then my `tlconfig.lua` looks like this:

```lua
return {
  skip_compat53 = true,
  preload_modules = {
    "love",
  },
  source_dir = "src",
  include = "*.tl",
  build_dir = "app",
}
```

When I run `tl build -p` I get the following output:

```
Would Write: app/input.lua
========================================
14 errors:
src/main.tl:1:1: module not found: 'setup'
src/main.tl:2:15: module not found: 'input'
...
Would Write: app/setup.lua
```

I omitted the rest of the errors because they stem from the fact that the modules couldn't be found for some reason, despite the fact that it knows about them, judging by the `Would Write`'s.

**Comment by Grinshpon** [comment]
Ah I figured it out just after submitting the issue, adding an `include_dir = { "src" }` t the `tlconfig` solved the problem.

**Comment by euclidianAce** [comment]
Hey, glad you figured out your issue, but I've also noticed your `include` is just a string instead of an array of strings. By default the `build` command just includes every `.tl` file it can find so in this case it works but it's technically ignoring your `include`. (additionally, build will only include `.tl` files so if you want to specify everything you can do the following)
so it should be `include = { "*" }`
Thanks for being detailed in your report! I'll submit a fix for this soon.

**Comment by Grinshpon** [comment]
oh that's my bad, thanks for the heads up!
