### ISSUE TITLE
tl build not striping requires to .d.tl files

### ISSUE THREAD

**Issue by lenscas** [teal-language/tl#241]
Looks like `tl build` doesn't strip away requires to .d.tl files, it also doesn't add similar files to keep lua happy
Project (and commit) I see it happen https://github.com/lenscas/card_game/commit/6673f3d7ea66fc7101cf2ab2d6ef72346dc70fb1

For example:

<details><summary>this is `types/Rust.d.tl`(hidden because its big)</summary>

```
local record RustTypes
    record Field
        -- pure Methods
        get_ai: function(Field):(Player)
        get_player: function(Field):(Player)
        has_ended: function(Field):(boolean)
        get_runes: function(Field):({HexaRune})
        -- Mutating Methods
        get_ai_card: function(Field):(Card)
        save_ai: function(Field, Player):()
        save_player: function(Field, Player):()
        save_rune: function(Field, HexaRune, number):()
        clean_up_runes: function(Field):()
        add_rune: function(Field, string):()
        -- Pure functions
        create_action: function(string):(PossibleActions)
        create_action_events: function(PossibleActions):(Action)
        create_event_list: function(Action, Action):(ActionsDuringTurn)

    end
    record Card
        -- pure Methods
        get_cost: function(Card):(number)
        get_speed: function(Card):(number)
        get_name: function(Card):(string)
        get_code: function(Card):(string)
        get_id: function(Card):(string)

    end
    record Player
        -- pure Methods
        get_mana: function(Player):(number)
        get_runes: function(Player):{SmallRune}
        -- Mutating Methods
        fill_hand: function(Player):()
        discard_cards: function(Player, number):()
        add_mana: function(Player, number):()
        sub_mana: function(Player, number):(boolean)
        deal_damage: function(Player, number):()
        heal: function(Player, number):()
        save_rune: function(Player, SmallRune, number):()
        clean_up_runes: function(Player):()
        add_rune: function(Player, string):()

    end
    record HexaRune
        -- pure Methods
        get_name: function(HexaRune):(string)
        get_turns_left: function(HexaRune):(number)
        id: function(HexaRune):(number)
        -- Mutating Methods
        dec_turns_left: function(HexaRune):(number)

    end
    record SmallRune
        -- pure Methods
        get_name: function(SmallRune):(string)
        get_turns_left: function(SmallRune):(number)
        id: function(SmallRune):(number)
        -- Mutating Methods
        dec_turns_left: function(SmallRune):(number)

    end
    record Action
        -- Mutating Methods
        add_trigger_before: function(Action, TriggerTypes):()
        add_trigger_after: function(Action, TriggerTypes):()

    end
    record ActionsDuringTurn
        -- Mutating Methods
        add_before: function(ActionsDuringTurn, TriggerTypes):()
        add_after: function(ActionsDuringTurn, TriggerTypes):()
        add_first_action: function(ActionsDuringTurn, Action):()
        add_second_action: function(ActionsDuringTurn, Action):()
        -- Pure functions
        create_trigger_small_rune_user: function(number):(TriggerTypes)
        create_trigger_hexa_rune: function(number):(TriggerTypes)
        create_trigger_small_rune_defender: function(number):(TriggerTypes)

    end
    record PossibleActions

    end
    record TriggerTypes

    end
end
return RustTypes
```
</details>

This is engine.tl
```lua
local Rust = require("types/Rust")

global battle : Rust.Field;
global chosenCard : Rust.Card;

require("engine/battle"):init(battle,chosenCard)
local turn = require"engine/turn"

return turn
```

After running `tl build` the generate engine.lua file looks like
```lua
local Rust = require("types/Rust")




require("engine/battle"):init(battle, chosenCard)
local turn = require("engine/turn")

return turn

```
No file that could be loaded with `types/Rust`in sight

Also, when using teal as a library, it also fails to load `types/Rust`, however the type checker works in that file and the vscode plugin also works as expected. So I don't think its a path issue.

**Comment by euclidianAce** [comment]
A quick workaround for this would be to rename your `.d.tl` file to just `.tl` since `require`ing it should have the same effect and `tl build` should see it. Although the purpose of `.d.tl` files is usually to annotate external Lua code, whereas inside of a project everything should be already annotated as a `.tl` file. Basically what I'm getting at is this is not an intended use case to have a `.d.tl` file for just defining some global types that you'd like, but maybe it should be?

cc @hishamhm, any thoughts?

**Comment by lenscas** [comment]
`Although the purpose of .d.tl files is usually to annotate external Lua code`
the types in `types/Rust` are types that come from the rust side of the application. If `.d.tl` is really only supposed to be for lua files, then how can I write type definitions for values that get injected into it? Because in my case the lua code is embedded in my rust code, rather than lua loading a library.

**Comment by euclidianAce** [comment]
If the `.d.tl` file provides nothing at runtime and is solely there for adding types for type checking, you can look into the `preload_modules` option for your `tlconfig.lua`, but make your types `global` rather than local.

so something like
```
-- tlconfig.lua
return {
   preload_modules = {
      "types/Rust"
   }
}
```
```
-- types/Rust.d.tl
global record Field
   -- [[ ... ]]
end
global record Card
   -- [[ ... ]]
end
-- etc.
```
And these types will be available to the type checker, without any runtime `require`s

**Comment by lenscas** [comment]
so, if I understand it correctly the requires are not stripped out because it expects a module to be available on the same path?

That makes them less nice than I thought they would be. I don't like the need to add global anything (I would have put the rust values behind a require or something if I could)

**Comment by euclidianAce** [comment]
> if I understand it correctly the requires are not stripped out because it expects a module to be available on the same path?

Yes, when type checking, if Teal finds a `require`, it will look for type definitions for type checking. Then, during runtime when Lua finds a `require` it will look for code to run.
So if your Rust module that you `require` in needs types, name a `.d.tl` file the same name as that module so the type checker can find its types.

> I would have put the rust values behind a require or something if I could

So the Rust values are globally loaded (or some table is globally loaded with access to rlua's userdata or something)? Then I would say it makes sense to include some global types. You can also namespace the types if you'd like with something like:
```
-- types/Rust.d.tl
global record Rust
   record Card

   end
   record Field

   end
end
```
And one thing to keep in mind is that globals (or anything) from a `.d.tl` file are *never* involved in the runtime of your program, just type checking. So if you're concerned about namespace pollution, this will hopefully mitigate that.

**Comment by hishamhm** [comment]
> cc @hishamhm, any thoughts?

@euclidianAce I think your suggestions here are :100: :+1:. Preloading a custom environment's globals from a .d.tl via tlconfig.lua is fine (I can imagine Love2D programs doing this because all the `love.*` globals are avaliable without requiring anything) and the explanation about compile vs runtime for require() is also on point.

> Yes, when type checking, if Teal finds a require, it will look for type definitions for type checking (by prioritizing .d.tl and .tl files). Then, during runtime when Lua finds a require it will look for code to run.

To put it even more concretely, when the Teal compiler sees a `require("foo")` which is resolved by Teal to a file `foo.d.tl`, the reason why it does not strip that is because generally you _want_ that require to stay, because at runtime Lua resolves it to either `foo.lua` or a binary module `foo.so` (typically written in C, but [not necessarily!](https://github.com/hishamhm/lua-syntect)).

Given @euclidianAce's explanations, I think we can close this issue, `require` calls should not be stripped.
