### ISSUE TITLE
tl doesn't remember 'in-project' files checked from `require`, resulting in code being loaded/checked more than once

### ISSUE THREAD

**Issue by virusdefender** [teal-language/tl#245]
the file structure is

```
tree
.
|-- tests
|   |-- test_cache.tl
|   `-- tests.tl
`-- tlconfig.lua
```

`tlconfig.lua`

```lua
return {
    include_dir = {
        "tests"
    }
}
```

`test_cache.tl`

```
global TestCache = {}

function TestCache.test_cache()
end
```

`tests.tl`

```
require("test_cache")
```

```
tl build
Wrote: tests/test_cache.lua
========================================
1 error:
tests/test_cache.tl:1:8: cannot redeclare global with a different type: previous type of TestCache is {test_cache: function()}
```

**Comment by hishamhm** [comment]
Looks like this doesn't happen on a flat file structure and `./tl check tests.tl`... @euclidianAce, any idea why this fails with `tl build` but not with `tl check`?

**Comment by euclidianAce** [comment]
Im not sure, probably has something to do with how the type checking environment is preserved and maybe that file is getting type checked twice and therefore declaring the same global twice? Ill try to test this later and nail the cause down.

**Comment by euclidianAce** [comment]
> Looks like this doesn't happen on a flat file structure and `./tl check tests.tl`

It still errors for me in a flat file structure. If I navigate to the `tests` directory and run `tl check *.tl`, the error is the same.

I think I may have found a lead on the issue though. It seems that when teal type checks a file brought in from `require`, it doesn't seem to remember that it already checked it, resulting in `test_cache` getting loaded twice leading to the redeclared global.

**Comment by euclidianAce** [comment]
After doing some more poking around, I'm like 90% sure this is the case.

**Comment by hishamhm** [comment]
> I think I may have found a lead on the issue though. It seems that when teal type checks a file brought in from require, it doesn't seem to remember that it already checked it, resulting in test_cache getting loaded twice leading to the redeclared global.

This leads me to a trickier question. If I run `tl check foo.tl bar.tl`, should that be equivalent to `tl check foo.tl; tl check bar.tl`? At first glance it seems so to me. The tricky bit becomes the behavior of globals. On the one hand, I don't think globals should leak from one file to the other during compilation like that -- if that was the case `tl check foo.tl bar.tl` and `tl check bar.tl foo.tl` could end up producing different results, which would be confusing. On the other hand, we do want to have some way to "inject globals without requires", which we have in the form of `preload_modules`.

It seems to me that when checking multiple files from the CLI, the behavior I expect is to have the environment completely cleared from file to file, but have `preload_modules` applied to each of them. If that sounds inefficient... well, it is, but declaring globals is the one compile-time side-effect we get from loading a module (either via `preload_modules` or `require`), and that side-effect needs to be applied. 

I seems that the current behavior, as you described with "tl doesn't remember", is that apparently what's happening is that the side-effects are lingering from file to file (the globals were declared), but tl doesn't remember that it did so and then tries again. Fixing that so it does remember is one solution, but then we'll get to the situation where the order of arguments in the CLI will change the order globals are declared. The alternative I'm proposing is to make it so that side-effects _don't_ linger from file to file (except for preload_modules, which would then have to be reapplied).

During a single `tl.process`, Teal does cache the modules as required, behaving like Lua:

```
-- m.tl
bug()
return {}
```

```
-- main.tl
local m1 = require("m")
local m2 = require("m")
local m3 = require("m")
bug2()
```

This reports on `m.tl` only once:

```
./tl check main.tl
========================================
2 errors:
.//m.tl:2:1: unknown variable: bug
main.tl:5:1: unknown variable: bug2
```

**Comment by hishamhm** [comment]
(Sorry, I started writing a comment, changed my mind halfway through, and then pressed the wrong button which dismissed the issue rather than the comment!)

**Comment by euclidianAce** [comment]
This should be fixed as of now, if the problem persists feel free to reopen this issue. Thanks for reporting!
