### ISSUE TITLE
(Lua 5.4) <const> and <close> attributes are not preserved

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/tl#252]
This is only really relevant for Lua 5.4, so maybe not a super high priority.

minimal example:
```
local x <close> = {}
```
generates
```
local x = {}
```

perhaps when running on 5.4 (or with a compiler flag like `--preserve-attrs` or something) it could preserve attributes? (for relevant locals at least)

**Comment by lenscas** [comment]
I think a way to set the target lua version is best, that way its possible for teal to error if the syntax isn't allowed for the target lua version (So, if you use the const attribute but the targeted lua version is < 5.4 then teal errors).

Additionally, it would also allow `tl run` to check the lua version before running, and refusing if it can't find the right one.

If teal wants to be really fancy it could then even load different .d.tl files for for the lua standard library, depending on the version selected and maybe even custom ones for if the specific lua version you use isn't supported out of the box by teal. (For example, though computercraft uses lua 5.1, some functions are removed, changed or replaced. If you can replace the types for the standard library then teal can be made aware of that)

**Comment by hishamhm** [comment]
> if you use the const attribute but the targeted lua version is < 5.4 then teal errors

The `<const>` attribute should be fine because Teal can actually statically verify that (so even dropping it is not that much of a problem, and preserving it for 5.4 targets shouldn't be problematic either), but the `<close>` attribute indeed would be problematic (if someone is writing code that relies on `<close>` semantics for correctness and then it is wiped away — it would be possible to generate code that sorta-kinda mimics `<close>` on Lua < 5.4 but it would never be 100% identical because of error paths (and we don't want to wrap everything around `pcall` all the time ;) )... but it could make things like the `lfs` directory iterator work so much nicer, so it's really tempting).

> If teal wants to be really fancy it could then even load different .d.tl files for for the lua standard library

I've been trying to avoid this through the use of compat-5.3. I want to avoid having "multiple Teal dialects" for as long as I possibly can. But of course, this can always be revisited over time.

**Comment by hishamhm** [comment]
@euclidianAce PR #506 closes this, right?

**Comment by euclidianAce** [comment]
Yep!
