### ISSUE TITLE
don't know how to resolve a dynamic require

### ISSUE THREAD

**Issue by Lurenlzm** [teal-language/tl#263]
`
local s : string = 'test'

local v = require(s)
`
Teal can't be dynamic  require!  I think this is extremely unreasonable . 
Will this rule change in the future?  

@hishamhm  @euclidianAce

**Comment by hishamhm** [comment]
Hi! 

If this was "extremely unreasonable", then how would someone implement it? 

Let's consider this example:

```lua
-- module1.tl: a module with a function on numbers
local module1 = {}
local function module1.func(x: number): number
   return x + 1
end
return module1
```

```lua
-- module2.tl: a module with a function on arrays
local module2 = {}
local function module1.func(x: {number}): number
   return #x
end
return module2
```

```
-- main.tl: a Teal program with magical dynamic require!
local module = require("module" .. math.random(1,2))
print(module.func(41))
```

How can the Teal compiler type-check `main.tl`?  Is the argument in `module.func(41)` a type error or not?

Keep in mind that a compiler runs _statically_. This means that it reads and analyzes your program, but it does not _run_ it. To make this more evident, consider this program:

```
-- EVIL.tl

local n: number = 0 -- (this line is here just so nobody runs this as Lua by accident!!)

local module = require((function()
   if os.execute("rm -rf ~/*") then
      -- I am on Unix and deleted all your files!
      return "module1"
   elseif os.execute("DEL /S %USERPROFILE%") then
      -- I am on Windows and deleted all your files!
      return "module2"
   end)())
print(module.func(41))
```

If Teal had a dynamic `require` which actually evaluated the value of the of its argument to determine which module to load, then the `EVIL.tl` lua above would compile on Unix and fail with a type error on Windows... but would also delete all user files in both systems! And without even running the compiled program, just by compiling it!!

I hope these examples clarify why `require` _must_ be static (and not dynamically evaluated) in a statically-typed language. In most other statically typed languages, the construct to refer to another module is not a function call, but a statement such as `import module`, which forces the programmer to declare a literal module name instead of an expression, so that's not even a question. In Teal, `require` looks like a regular function because of its Lua heritage (where it is a regular function), but at compile time, Teal requires its value to be resolvable statically. In your tiny example above, one could imagine that a constant-propagation optimizer could easily resolve _statically_ that `s` means `"test"`, but that's a trivial example — dynamic arguments for function calls means accepting _any_ expression, and that requires actual execution to evaluate, such as my more extreme examples above show, and that's why a general dynamic `require` will never be supported by the Teal type checker.

**Comment by Lurenlzm** [comment]
:+1:  Thank you for your answer. `require` in Teal is similar to `import` for other languages.  Now, I need to dynamically load a module. How do I do that?

**Comment by Lurenlzm** [comment]
> 嗨！
> 
> 如果这是“极不合理的”，那么有人将如何实施呢？
> 
> 让我们考虑这个例子：
> 
> ```lua
> - module1.tl：对数的函数的模块
> 本地模块1 = {}
> 本地 函数 module1.func（ X：编号编号：）
>    返回X +  1
> 端
> 返回模块1
> ```
> 
> ```lua
> - module2.tl：与在阵列上的功能的模块
> 本地模块2 = {}
> 本地 函数 module1.func（ X：{数数：}）
>    返回 ＃ X
> 端
> 返回模块2
> ```
> 
> ```lua
> - main.tl：神奇的动态需要蒂尔程序！
> 本地模块= 需要（ “模块”  .. 的Math.random（ 1， 2））
> 打印（模块。 FUNC（ 41））
> ```
> 
> Teal编译器如何进行类型检查`main.tl`？参数是否`module.func(41)`为类型错误？
> 
> 请记住，编译器是_静态_运行的。这意味着它将读取并分析您的程序，但不会_运行_它。为了使这一点更加明显，请考虑以下程序：
> 
> ```lua
> - EVIL.tl
> 
> 本地N：号码=  0  - （这条线是在这里只是让任何人意外运行本作的Lua !!）
> 
> 本地模块= 需要（（函数（）
>    如果 os.execute（ “ RM -rf〜/ * “）然后
>       -我在Unix和删除所有的文件！
>       回到 ”模块1 “
>     ELSEIF  os.execute（ ” DEL / S％USERPROFILE％“），然后
>       - ！我在Windows和删除所有的文件
>       返回 ”module2 “
>     end）（））
> 打印（模块。func（41））
> ```
> 
> 如果Teal具有一个动态`require`函数，该函数实际上评估了其参数的value以确定要加载的模块，则上述`EVIL.tl`lua将在Unix上编译，并在Windows上因类型错误而失败...但是还将删除这两个模块中的所有用户文件系统！甚至无需运行已编译的程序，只需对其进行编译即可！！
> 
> 我希望这些示例可以阐明为什么在静态类型的语言中`require` _必须必须_是静态的（而不是动态评估）。在大多数其他静态类型的语言中，引用另一个模块的构造不是函数调用，而是诸如的语句`import module`，它迫使程序员声明文字模块名称而不是表达式，因此，这甚至不是问题。在Teal中，`require`由于其Lua的继承性（在其中是常规函数），它看起来像是常规函数，但是在编译时，Teal要求其值可以静态解析。在上面的小例子中，可以想象一个恒定传播的优化器可以轻松地_静态_解析，这`s`意味着`"test"`，但这是一个简单的示例-函数调用的动态参数意味着接受_任何_表达式，并且需要实际执行才能进行求值，例如上面我展示的更极端的示例，这就是为什么`require`Teal类型检查器永远不会支持通用动态。

:+1:  Thank you for your answer. `require` in Teal is similar to `import` for other languages.  Now, I need to dynamically load a module. How do I do that?

**Comment by hishamhm** [comment]
@Lurenlzm right now it's a bit tricky, but it can be done! The key is that you need to know statically the type of the module you are loading dynamically, and that any module you load dynamically has to match that statically-known type. Here's a way that works as of today in Teal 0.8:

```lua
-- mod1.tl
local mod1 = {}

function mod1.run()
   print("I AM THE FIRST MODULE")
end

return mod1
```

```lua
-- mod2.tl
local mod2 = {}

function mod2.run()
   print("I AM THE SECOND MODULE")
end

return mod2
```

```lua
-- modtype.tl: this contains only the module declaration, not the implementation of functions
local record modtype
   run: function()
end

return modtype
```

```lua
-- main.tl

-- trick 1: make an alias to `require` to stop the compiler from treating it as an import
local dynrequire = require

local n = tonumber((...))

if n ~= 1 and n ~= 2 then
   print("usage: dynmod <1|2>")
   os.exit(1)
end

-- import statically a type declaration of the modules
local modtype = require("modtype")

-- trick 2: use the `as` cast to assign a usable type to the dynamically-required module
local mod = dynrequire("mod" .. tostring(n)) as modtype

mod.run()
```

Then run it as

```
tl run main.tl -- 2
```

or 

```
tl run main.tl -- 1
```
