### ISSUE TITLE
Using the type declaration syntax prevents nominals from being properly resolved

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/tl#269]
minimal example:
```
local type A = number
local type B = A

local function foo(bar: A)
end

local var: B
foo(var)
```
`tl check`:
```
========================================
1 error:
blah.tl:9:5: argument 1: B is not a A
```
except that `B` is exactly `A`, so i would imagine that this should work.
Additionally, i believe this is what prevents us from using `local type ... = ...` here
https://github.com/teal-language/tl/blob/e769dc803e8eb06f4e1f16489d01f92a02dc2c19/tl.tl#L48-L50
Which would help clean up generated code, which shouldn't have any traces of non-record definitions

**Comment by hishamhm** [comment]
I have not looked at the internals for this, but from the outside it looks like the implementation currently has the following behavior which, full disclosure, happened accidentally:

* `local type B = A` — B is a new type that has the same structure as A, but is unrelated to A
* `local B = A` — B is an alias to A, they are the same type

There are languages that _do_ make this distiction between new types and aliases on purpose, providing distinct syntax for each case.

I'm still thinking whether this distinction is a useful thing to have. I'm currently unconvinced and inclined to treat this as a bug, and change the behavior of `local type B = A` so that it has the same "alias" behavior that `local B = A` had, as you (and I) expected.

(But note that declaring types with `local type A = record...` and `local type B = record...` should still produce distinct unrelated types even if their structures are identical.)

**Comment by hishamhm** [comment]
Going ahead and labeling this as a bug.

(i) `local type` behavior

```lua
 local type Error = tl.Error 
```
should work the way

```lua
 local Error = tl.Error 
```
works above, and produce a usable alias for the type.

(ii) `local` behavior

```lua
 local Error = tl.Error 
```

should produce a variable of that type, with the type's "prototype object" assigned to it.

I know that people sometimes find it weird that the type declarations produce a table in Lua code (it is kinda weird; the normal thing would be to erase types completely), but I think that producing that "prototype object" is consistent, once you consider code such as:

```lua
local record R
   -- ...
end

function R.func()
 -- ...
end
```

We are creating a field `func` in a Lua table `R`, after all. As such, the `R` object is a Lua table, and as such it should be possible to assign it to a variable, etc. (But if the programmer goes out of their way to mess up the record definiton with things such as `R.func = nil`, they are on their own.)

**Comment by hishamhm** [comment]
I spent the whole day coding experiments, taking long walks and thinking about this (which, needless to say, I enjoy — PL design is fun :) ). I had a much longer comment written at one point, but I kept editing it. The short version, for now, is that right now I disagree with my comment above :) and I'm thinking that the current behavior of `local type` always creating a new type is probably for the best in a nominal system. I implemented a hybrid behavior where `local type Name = AnotherName` would create an alias for nominals (and a new type for other types), but it's weird plus generics make this really messy. As for aliases, plain `local T1 = T2` works okay right now but does not support pinning generics (`local T1 = T2<T3>` is a syntax error, even). Not sure if that's a big problem and if we need an actual "type alias" construct.

Will keep this open and still think about it some more!
