### ISSUE TITLE
Question: Will Teal evolve to support other languages than Lua?

### ISSUE THREAD

**Issue by felipedaragon** [teal-language/tl#272]
First of all, congratulations for the project, Hisham! I'm impressed. You probably know that TypeScript has been evolving to transpile to other languages than JavaScript, there is even Lua transpilation already https://github.com/TypeScriptToLua/TypeScriptToLua 
This made me think about a project that could compete with TypeScript when it comes to transpilation to other languages. So this brings my question: do you believe that Teal may evolve to support other languages than Lua?

**Comment by lenscas** [comment]
technically, there is probably little stopping teal from doing so but... I don't see the point.

**Comment by felipedaragon** [comment]
@lenscas technically, perhaps, it is possible. I would love to hear the author's opinion. This kind of transpilation from TS allows someone to write a code that can target multiple different environment and scripting languages, make it easier to switch from a language to another, among other things: https://aws.amazon.com/blogs/opensource/generate-python-java-dotnet-software-libraries-from-typescript-source/

**Comment by CapsAdmin** [comment]
TypeScriptToLua is not an official project from the Typescript team or Microsoft. I guess you could start a similar unofficial TealToTypescript project if you want.

It would probably help if Teal supports swapping out the code emitter. I assume this is not on the roadmap at the moment.

**Comment by felipedaragon** [comment]
@CapsAdmin yeah, i know it is not an official project from MS. actually transpiling Teal to TypeScript would probably not be a good idea, since you would have to transpile it again... What I meant was really having Teal as an alternative to TypeScript when dealing with transpilation to JS, and other languages than JavaScript. Of course, this would redefine a bit what the Lua language is... since we know it is a powerful language because of its cross-environment compatible VM, C API, and when you transpile to another language much of that is lost, but not the simplicify of the language, and who knows, maybe Lua could become powerful in new directions that we cannot anticipate right now

**Comment by hishamhm** [comment]
>  do you believe that Teal may evolve to support other languages than Lua?

It's not on my plans. Compiling into other languages would be a lot more work than compiling to Lua, because Teal pretty much assumes that the underlying runtime semantics of the target language (Lua) matches its own. For example, translating a Teal array into JS is not equivalent to translating to a JS array: you have to make sure that all quirks of Lua arrays are perfectly preserved, otherwise you produce different behavior when changing build targets. And that's just one easy example: think of harder cases such as coroutines and GC finalizers.

For running Teal on top of JS, it makes more sense to use Teal as a frontend to Fengari, as done by the [Teal Playground](https://teal-playground.netlify.app/) ( https://github.com/teal-language/teal-playground/ )

Having said that, in the Titan project we did explore the idea of compiling a Teal-like language to C, but to retain semantics we actually included parts of the Lua VM in it, so that for example, the table implementation was actually Lua's. This could be something worth revisiting in the future, resulting in an ahead-of-time native-code compiler for Teal. But it's not on my horizon to pursue that (though I'd _love_ if somebody gave it a shot!)

**Comment by hishamhm** [comment]
Closing this one since I believe the question has been answered. If anyone else has further thoughts on the topic, feel free to comment here!
