### ISSUE TITLE
mechanism to avoid duplicate lua file generation

### ISSUE THREAD

**Issue by virusdefender** [teal-language/tl#302]
tl will re-generate all files if you run `tl build` even if there is only one file changed in the whole code base.

one approach is inserting a simple comment contains the hash of corresponding tl file like

```lua
--[[source-hash: sha256-value]]
```

**Comment by lenscas** [comment]
not to be rude, but why?

if you put the hash in the lua file teal still needs to parse the .tl files to make sure the types of the other files that load it are still correct. I'm also not sure if it actually saves time, as now you first need to read the first part of every file and calculate the hash as opposed to just writing everything.

If teal gets the ability to do partial builds I suggest that it writes special files to a new folder that contain just the type information and are in a format that is super easy to parse (May even be a binary file as the user is not supposed to work with them). I also suggest to write down the last build time and compare the last editted date with the last build time.

**Comment by hishamhm** [comment]
I think the suggestion described by @lenscas is the way to go.

Teal may need the type info of other files that were compiled previously as they are required, so caching the type information of modules would be cool.

But even without that, checking timestamps to build only newer files would already be an improvement (even if it still does some duplicate work due to require dependencies). So these could be implemented as two separate improvements.

**Comment by euclidianAce** [comment]
So my cli does this already and the reason I haven't ported the feature over is I can't really think of a way to quickly parse dependencies. In mine I pull in ltreesitter and tree-sitter-teal so I can just query for require calls with literal strings and have the names of the modules handed to me on a silver platter. If the parser were able to include any string literal arguments to `require` it finds in the `Result` I'd be happy to port this to the official cli.

Given that, building up a graph of file dependencies is almost trivial and timestamps don't need to be stored as you can just compare the timestamp of the `tl` file to the `lua` file and see if its newer. Additionally you have to remember to re-typecheck the dependents of a file whenever it changes if you want to do incremental rebuilds, but my cli builds the graph so that nodes point at the dependent nodes (as done by the [tup build system](http://gittup.org/tup/)) which makes it easy to do things incrementally.

In fact it might be easy enough for me to just implement :P I'll give it a shot soon, but as the cli gets more featureful, the more I want to split it off into its own repo and I don't think the `tl` api is good enough for that yet

**Comment by lenscas** [comment]
my question: Are partial builds worth it right now? Are there projects that people work on where the performance of the compiler is a hindrance as it currently is?

My experience so far has been that teal is plenty fast as is, though maybe I'm simply not pushing it yet?

**Comment by hishamhm** [comment]
> Are there projects that people work on where the performance of the compiler is a hindrance as it currently is?

I tried once to run the Busted tests as .tl instead of .lua — Busted regenerates the sandbox environment every time, meaning that each `local tl = require("tl")` was a fresh require, which ran the type checker and compiler. parsing+typechecking+codegen of `tl.tl` takes 0.3s on my machine; running that for each file of the test suite added up quickly beyond feeling usable. I think a quick timestamp check against the .lua file in the tl package loader would have addressed that.

**Comment by hishamhm** [comment]
> If the parser were able to include any string literal arguments to require it finds in the Result I'd be happy to port this to the official cli.

Should be pretty easy to do that in `require_module`, which has the `Result` and the `module_name` literal handy!

**Comment by hishamhm** [comment]
Closing this one since https://github.com/teal-language/cyan is able to do this and works as a replacement for the `tl build` command!
