### ISSUE TITLE
playgrounds which use forks seem to be broken.

### ISSUE THREAD

**Issue by lenscas** [teal-language/tl#306]
https://hishamhm-545915275--teal-playground.netlify.app (from https://github.com/teal-language/tl/pull/299  the page loads, but it looks like `tl` is not found

https://euclidianace-546672211--teal-playground.netlify.app/ (from https://github.com/teal-language/tl/pull/304) you get a 404

this one seems to work though, weirdly enough
https://lenscas-546325786--teal-playground.netlify.app/ (its from https://github.com/teal-language/tl/pull/301 )

**Comment by hishamhm** [comment]
I have no idea how the lifetime of these playgrounds work; I assumed they would be temporary. @darrenjennings, any insights?

> https://hishamhm-545915275--teal-playground.netlify.app (from #299 the page loads, but it looks like tl is not found

I think this one is understandable, because the PR was merged and I deleted the branch, meaning the URL that points to it, used by the playground, is now broken.

> this one seems to work though, weirdly enough
https://lenscas-546325786--teal-playground.netlify.app/ (its from #301 )

Yours is a fork, so I think playgrounds using forks _do_ work?

Not sure what to do with the second example, might as well be a fluke. Can we close this one, and if more cases of "not found" happen, then we reopen and investigate?

**Comment by darrenjennings** [comment]
@hishamhm is right, old merged pr's will no longer work because they rely on the github hosted files of the deleted pr branch. Not sure if there is a good way to get around that unless we go to the trouble of checking if the files exists first. I assume the ephemeral nature of the playgrounds is acceptable. But, I am unsure why pr 304 404'ing. I went ahead and reran the job and it is still 404'ing.

**Comment by hishamhm** [comment]
Agreed. Thanks for the clarification! Let's close this and only spend more time on this if 404's become recurring.
