### ISSUE TITLE
odd "got 'type', expected {}" in map declaration

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/tl#318]
example:
```
local map: {boolean:{number}} = {
	[true] = {},
}
print_type(map)
```
```
$ tl check blah.tl
({boolean : {number}})
========================================
2 errors:
blah.tl:2:22: in local declaration: map: got {number}, expected {}
blah.tl:5:1: unknown variable: print_type
```
This only seems to happen when the keys are of a certain type. For example, `number` keys are just fine
```
local map: {number:{number}} = {
	[3] = {},
}
```
type checks just fine

Additionally, it seems like some `same_type`/`is_a` arguments are in the wrong order somewhere as the intent here seems like it should be `got {}, expected {number}`

**Comment by hishamhm** [comment]
> For example, number keys are just fine

this is because this

```
print_type({
   [3] = {},
})
```

prints `({{}})` and the other one prints `({boolean : {}})`, so it definitely has to do with map-specific behavior. Thanks for the report, looking at it!

**Comment by euclidianAce** [comment]
@hishamhm I've been poking around a little bit and i think the issue may be around line 5403 when `is_a`, checks a map to a map, the keys are checked as `t1.keys <: t2.keys` but the values are checked `t2.values <: t1.values`

**Comment by hishamhm** [comment]
@euclidianAce yes, but that was intentional. a map `{a:b}` is equivalent to a function `a -> b`, so the (covariant) subtyping relationship is that input is covariant and output is contravariant. I'm reviewing the rules and the places where it's being used; might be something specific to `emptytable`.

**Comment by euclidianAce** [comment]
I've been meaning to brush up on some type theory (i.e. ignore this if im completely wrong :laughing:), but from some rudimentary googling https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)#Function_types appears to state the opposite, that input is contravariant and output is covariant.

Swapping them seems to fix this issue, but makes a couple of the other tests fail

**Comment by hishamhm** [comment]
@euclidianAce haha, yes! I totally got that flipped and came to realize that while fixing this.

https://github.com/teal-language/tl/pull/319

> Swapping them seems to fix this issue, but makes a couple of the other tests fail

One of the tests had its error message flipped, the other failure had to do with an ugly hack there to deal with `{any:any}`. I'll explain. This looks reasonable, right?

```
local any_anys: {any: any} = { [true] = { "foo" } }
```

After all, all you want for `t` is to be a "bag of anything". But then what about this:

```
local bool_strings: {boolean:{string}} = { [true] = { "foo" } }
local any_anys: {any: any} = bool_strings
```

You're assigning the same thing. Should the above work? What about:

```
any_anys[true] = 2 -- valid for {any:any}, but now we broke bool_strings!
```

However, one thing I missed earlier is that maps are different from functions in that in `a -> b`, `a` is only "read" and `b` is only "written" by the function. In maps, however, you have both reading and assignment operations to both keys and values. So, even if we flip the above example, we have problems:

```
local any_strings: {any: string} = { [true] = "hello", [2] = "world" }
local bool_anys: {boolean: any} = anys
print(bool_anys[true]) -- OK for reading
bool_anys[false] = 123 -- we broke any_strings!
```

```
local bool_anys: {boolean: any} = { [true] = "hello", [false] = 2 }
local any_strings: {any: string} = bool_anys
print(any_strings[false]) -- broken!
```

And to complete, the fourth case:

```
local any_anys: {any: any} = { [2] = "hello", [false] = 3 }
local bool_strings: {boolean: string} = any_anys
print(bool_strings[false]) -- broken!
```

The conclusion is that for read-write maps, the only sound compatibility rule is `same_type`: they need to be invariant on both keys and values.

Once we start adding more subtyping relationships (e.g. `interface`s, etc.) these restrictions will start to hit us harder. I am planning to add variance annotations to the language so that you can say "I promise I will only read from this", which would allow things like:

```
local any_strings: {any: string} = { [true] = "hello", [2] = "world" }
local bool_anys <out>: {boolean: any} = anys
print(bool_anys[true]) -- OK for reading
-- bool_anys[false] = 123 -- can't write to bool_anys, can't break any_strings!
```

These "in" and "out" annotations will be needed for function arguments too.

Back to "any": there's a hack in the map is-a implementation regarding "any". There the `any` type is currently being used not as a proper [top type](https://en.wikipedia.org/wiki/Top_type), but as an unsound escape hatch. This is a remnant from the earliest days of tl (recall it was written it itself from early on), and to this day the word `table` when used as a type magically translates to `{any:any}` (see parse_base_type), but I think we should remove this sooner rather than later.

**Comment by euclidianAce** [comment]
Yeah, I was starting to come to the conclusion that you have, but you've explained it much better than I would have. Also I've realized that my mental model for any has been as both a top and bottom type, which I guess is basically the same as what you describe as it `any <: T <: any` => anything, which is definitely unsound

> I am planning to add variance annotations to the language so that you can say "I promise I will only read from this"

If you want it to be applicable to function args too, wouldn't it make sense for that to be a type modifier rather than a variable attribute? This is what Ada does (and I assume this is where you got the name for the \<out\> annotation from). This is something I've wanted to play around with by making types fully fledged expressions that have to be evaluated. So in `x: out {boolean:any}` the `out` would be a unary operator on types.

Also `const` could apply to types as well, but then you get into some of the same weirdness that C has with mutable pointer to const data vs const pointer to mutable data, though the syntax for type annotations and variable attributes definitely gets rid of this ambiguity and would maybe be worth it? like:
```
local x: const {number} = {1, 2, 3} -- frozen array, x[1] = 2 illegal, x = {3, 2, 1} legal
local y <const>: {number} = {1, 2, 3} -- x[1] = 2 legal, y = {3, 2, 1} illegal
```
which I guess makes a `const` type the same as an `out` type that you described?

**Comment by hishamhm** [comment]
Good food for thought! There are pros and cons for doing things in variables or types (types are assigned to values, and then you need to take aliasing into account; variables are easier to keep track; nested values also need to be taken into account; nested types as well, generics, etc.).

One lightweight possibility is to make `in` and `out` annotations just check subtype-validity for assignment (including assignment of function arguments), but not check the actual operations, and it's up to the programmer to use them safely (after all, you can block `t[x] = v` with an annotation, but can you really block `setter(t, x, v)`? That could be one first approximation to the subtyping question. Since we're coming from Lua where _everything_ is up to programmer's discipline, we can do baby steps with incremental improvements.
