### ISSUE TITLE
how to create a multiple return value type

### ISSUE THREAD

**Issue by darrenjennings** [teal-language/tl#324]
How would you go about typing this in teal?

[link to playground](https://teal-playground.netlify.app/?c=bG9jYWwgcmVjb3JkIFNlc3Npb248RGF0YT4KICAgIGRhdGE6IERhdGEKZW5kCgpsb2NhbCB0eXBlIE15U2Vzc2lvbkRhdGEgPSB7c3RyaW5nLCBzdHJpbmcsIHtzdHJpbmd9fQpsb2NhbCB0eXBlIE15U2Vzc2lvbiA9IFNlc3Npb248TXlTZXNzaW9uRGF0YT4KCmZ1bmN0aW9uIHJldHJpZXZlX3Nlc3Npb25fZGF0YShzOiBNeVNlc3Npb24pOiBNeVNlc3Npb25EYXRhIC0tIHRoaXMgZG9lc24ndCB3b3JrCiAgcmV0dXJuIHMuZGF0YVsxXSwgcy5kYXRhWzJdLCBzLmRhdGFbM10KZW5k)

```lua
local record Session<Data>
    data: Data
end

local type MySessionData = {string, string, {string}}
local type MySession = Session<MySessionData>

function retrieve_session_data(s: MySession): MySessionData -- this doesn't work
  return s.data[1], s.data[2], s.data[3]
end
```

**Comment by hishamhm** [comment]
The confusion here comes from mixing tuples and multiple returns.

You declared `MySessionData` to be a tuple array: a tuple in Teal is a Lua table with a known array size (in this case 3) with potentially heterogeneous types.

A function with multiple returns is not a function returning a tuple, just like a function with multiple input arguments is not a function taking a tuple on input. As such, there is no way to give a single name to mutiple returns, because it's not a type, it's really multiple types. Again, this is similar to why you can't give a single name to multiple input arguments.

(This behavior of multiple returns is different from other languages such as Python. Lua has actual multiple returns, not simulated multiple returns via a single tuple object that is then destructured on assignment.)

There are a few ways to make that function typecheck:

```lua
function retrieve_session_data_1(s: MySession): MySessionData
  -- you're returning a MySessionData tuple,it works if you wrap it as a tuple
  return { s.data[1], s.data[2], s.data[3] } 
end

function retrieve_session_data_2(s: MySession): MySessionData
  -- the data attribute of a Session<MySessionData> is a MySessionData
  return s.data
end

-- if you want to return multiple items, give it multiple return types
function retrieve_session_data_3(s: MySession): string, string, {string}
  return s.data[1], s.data[2], s.data[3]
end
```

**Comment by darrenjennings** [comment]
@hishamhm that is helpful! I was hoping to do something like `function retrieve_session_data_1(s: MySession): MySessionData[0], MySessionData[1], MySessionData[2]` but actually changing the implementation's return to fit a tuple type is probably better.

**Comment by hishamhm** [comment]
@darrenjennings what is this `[0]` thing you speak of? :grin:

**Comment by lenscas** [comment]
feature request: have a feature that automatically increments any array access with +1 so arrays start at "0" :P 

(Its a joke, please don't do this...)
