### ISSUE TITLE
Cannot declare a record field and a record subtype with the same name

### ISSUE THREAD

**Issue by overcrook** [teal-language/tl#370]
I'm currently have several JSON schemas and Teal/Lua scrips to work with.
At the moment I have to manually declare all records and fields for Teal to work properly, but this approach is error-prone. So I decided to create a Teal type definition generator.

But it seems to impossible to declare a record subtype AND a field of that type with the same name. For instance:

```
local record Response
   record Result
      TransactionID: string
   end

   record Error
      Code: number
      Message: string
   end

   Result: Result
   Error: Error
end
```

But at the same time I can declare a local variable with type of a record with the same name:

```
local record Foo
   bar: boolean
end

local Foo: Foo
Foo.bar = true
```

I digged through `tl.tl` and found that the fields and subtypes of the records go into the same table `fields`. So this looks like a bug / misinterpretation in the compiler. Or is this intended behavior?

**Comment by overcrook** [comment]
As a workaround I simply add the letter `T` at the beginning of the generated type name, so this issue does not bother me much.
But I`d like to hear your opinion about this.

**Comment by hishamhm** [comment]
@overcrook It is intended behavior, because Teal records (and sub-records) are concrete Lua tables. This is intended to capture common Lua patterns such as prototype-based OOP and class-based OOP where the class table is used to hold "static" (in the Java sense) attributes and functions.

> `local Foo: Foo`

This is allowed, but it produces a warning, and the local variable `Foo` is shadowing type `Foo`, so if you try to do `local x: Foo` in the following line, it produces an error "uknown type Foo". Types and variables live in the same namespace, and that's by design.

If you have control over your JSON schema fields, I'd suggest a convention of lowercase attributes and uppercase types, as in `result: Result`, but if you need to comply to an existing schema for attribute names, then the approach you've taken with `Result: TResult` should work.

Hope that helps!

**Comment by overcrook** [comment]
OK, thanks for the detailed explanation!
