### ISSUE TITLE
Remote debugging experience

### ISSUE THREAD

**Issue by DrSensor** [teal-language/tl#374]
Hi, does Teal works with [LRDB](https://github.com/satoren/LRDB)?
Or maybe is there a workaround on this?

**Comment by lenscas** [comment]
yes and no.

It works in so far that you can use it to debug the generated lua however you can write whatever you need to get it to work in teal.

**Comment by DrSensor** [comment]
Is it necessary having or generate something like sourcemap to make the debugging experience seamless?

**Comment by lenscas** [comment]
the teal compiler does it best so that the line numbers of the `.tl` file and the corresponding `.lua` file match. To my knowledge it also tries to limit the amount of changes done to the generated lua compared to the teal file. So, it should be pretty easy to map without a source map.

**Comment by mingodad** [comment]
It doesn't seem to be the case with the ´./tl.tl´ as noticed here https://github.com/teal-language/tl/issues/376

**Comment by hishamhm** [comment]
@mingodad not sure what you mean. @lenscas is right: Teal definitely maps every input line from `tl.tl` to an output line in the same location in `tl.lua`, and stack traces produced point to the correct locations precisely (I should know, I keep seeing those traces when developing it! :grin: )

@DrSensor if you run `tl.loader()` from main your Lua application to install as a package loader, loading Teal files with `require()` will load them with the `.tl` filename into Lua's memory even, so the stack traces will even refer to the `.tl` files directly. The same behavior happens running `.tl` files from the CLI with `tl run`, so it's easy to observe:

```
$ cat crash.tl 
local function g(x: number)
   print("let's crash...")
   error("crash here! number was " .. x)
end

local function f(x: number)
   g(x)
end

local function lets_go(n: number)
   f(n)
end

lets_go(123)

$ ./tl run crash.tl
let's crash...
lua: crash.tl:3: crash here! number was 123
stack traceback:
	[C]: in function 'error'
	crash.tl:3: in upvalue 'g'
	crash.tl:7: in upvalue 'f'
	crash.tl:11: in local 'lets_go'
	crash.tl:14: in main chunk
	(...tail calls...)
	[C]: in ?

```

**Comment by hishamhm** [comment]
Took a quick look at the LRDB docs. Looks like it's designed to be called from a host C++ application that uses the Lua C API.

If instead of using `luaL_loadfile` you (1) compile from .tl to .lua at build time, (2) load the text of your compiled .lua scripts from C++ yourself and then (3) use `lua_load` to read them but set the `chunkname` argument to your .tl file, you will produce executable Lua chunks that point to the .tl sources in their debug info, effectively getting the same result as using `tl.loader()`, but without the time penalty of Teal compilation at runtime. The LRDB VS Code extension should happily point to the Teal code.
