### ISSUE TITLE
type aliases in records cause compiler crash

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/tl#416]
On the latest master:
```
local type A = number
local record Foo
   type B = A
end

local foo: Foo.B
print(foo)
```
produces a crash with `lua: /home/corey/dev/tl/tl.lua:5758: assertion failed!` , interestingly, commenting out the print makes this check fine. With some quick poking around it seems like either
 - at some point a `t.found` is being assigned the wrong value or `find_type` is not finding the correct value for when the type is in a record (and something to do with the `nestedtype` type)

**Comment by hishamhm** [comment]
> interestingly, commenting out the print makes this check fine

Hehe, that's because of a little untold "secret", that resolution of nominals is actually lazy (that's why circular references work within the same compilation unit — but don't quote me on that, that's undocumented behavior that's currently an implementation detail! I think we need to fix that and add an actual syntax for forward references that works across compilation units (and also allows hiding the implementation, but that's beside the point)).

I added that assert to make sure that type aliases don't produce a linked list of indirect references. So a `local type` actually resolves the lazy reference (see `resolve_nominal_typetype` in the `["local_type"]` and `["global_type"]` callbacks.

So, the fix for that problem is to do the same and resolve the nominal strictly in the `["record"]` callback for visit_type. Note that this means that circular references in them won't work, but hey, they're crashing today, so it's not like anyone's depending on that working. :) (Plus, circular references need the proper solution as mentioned above.)

(The alternative would be to remove the assert and make `resolve_nominal` recurse, but I don't want to do that because it complicates things with scopes, as nested type aliases could nominal-reference things that will be out of scope by the time the lazy usage triggers it.)

I'll try this fix and see if it does the trick. Thank you for the clear report and investigation!

**Comment by hishamhm** [comment]
Fixed it, but added a restriction in use which I don't expect to hit people seriously (see test cases in the commit for details):

> * Allow using nested type aliases only in a type context, and
>   not in a value context as prototypes. This avoids complications
>   with code generation.

Thanks again!
