### ISSUE TITLE
Type alias on preloaded modules

### ISSUE THREAD

**Issue by Mephistophiles** [teal-language/tl#421]
If we create a local type (alias) from a preloaded module, Teal creates a variable with a full path of type in the Lua code.  Because of this, an error occurs in the runtime:
```
attempt to index a nil value (global 'Struct') 
```

How to reproduce:

example.tl
```lua
local type b = Struct.b

function test(t: b)
end
```
preloaded.d.tl
```
global record Struct
   a: number
   record b
      a: number
      b: number
   end
end
```

```shell
tl gen --check --preload preloaded  example.tl
```

Teal generates the following code:
```lua
local b = Struct.b


function test(t)
end
```

**Comment by hishamhm** [comment]
This is more confusion arising from the "preload" functionality... (I have commented quite a bit about this in the Gitter/Matrix chat). :confused: That feature was intended only to predefine globals that already exist in your VM environment (such as the `love` global in Love2D apps or `ngx` in OpenResty apps), not to spare modules from using `require()` to load types (which would be bad for modularity).

Teal records have a concrete Lua table as a reification (which is needed for things like prototype-based OOP and declaring functions). You should not use `preload_modules` to declare global records in Teal that to not have an equivalent Lua table already in the environment.

The solution to the issue above is to not try to use `--preload` for that end. Instead, add a `Struct.tl` to your project, using `local record` and `return Struct` instead of `global`, and then using `local Struct = require("Struct")` in other modules that use it.

We are fixing the documentation (it used to say that "preload_modules runs the equivalent of require()", which was incorrect), and we will rename the functionality in the next release, to reduce the confusion.

**Comment by Mephistophiles** [comment]
Thanks for the clarification. In this case, I wanted to reduce the number of explicit requires.
