### ISSUE TITLE
table.concat expects {string} instead of {string|number}

### ISSUE THREAD

**Issue by shviller** [teal-language/tl#450]
Lua's reference manual [says](https://www.lua.org/manual/5.3/manual.html#pdf-table.concat)
> Given a list where all elements are strings or numbers, returns the string...

However,
```lua
local vector = {1,2,3}
print(table.concat(vector, ','))
```
causes Teal to error with
```
argument 1: got {integer}, expected {string}
```

**Comment by hishamhm** [comment]
Thanks for reporting! This should be an easy fix, by updating the definition of `concat` in the `standard_library` table to make it accept an array of `string | number` rather than an array of `string`, and then adding a small test in `spec/stdlib/table_spec.lua`. If anyone wants to try their first contribution to the codebase, this is a good one to start :)

**Comment by FredericoGauz** [comment]
Hi hishamhm, I was thinking about learning about the project. I will take a look and see what I can do...
