### ISSUE TITLE
Better Story/Docs for Environment Globals

### ISSUE THREAD

**Issue by tooolbox** [teal-language/tl#454]
Teal has `global_env_def` in the config that allows you to specify a `.d.tl` file to define modules that are already available in the environment, i.e. do not need a `require()` call.  Such `.d.tl` files are structured as records.

What's not really clear or maybe there's no simple method for this is when your environment contains straight globals that aren't used like `local application = require("application"); application.quit()`  What if it's just `quit()`?

I did eventually manage to get this working by defining `global` functions in my `.d.tl` that had no body, just the signature and `end` but this seems rather hacky.  Thoughts?

**Comment by euclidianAce** [comment]
You can just define the symbol and type like so
```
global quit: function()
```
without having to give an empty body.

What point I think needs to be driven home is that the type system doesn't care about the values of variables. If you want the type system to know about something all you need to do is put a declaration for it, which for any non record or enum should be as simple as
```
local foo: <insert type here>
-- or
global bar: <insert type here>
```

**Comment by tooolbox** [comment]
Great, that's what I was missing.  Specifically, I had to say `global bar: <type>` rather than just `bar: <type>` which errors.  Part of the problem here is that all of the examples I looked at, in the teal-types repo, were records and records can define their members as `bar: <type>`.  I think I saw `global` by accident in some test code for the `global_env_def` feature.

A factor against me is that I'm fairly new to Lua in general.  It seems like `global` is a Teal thing, not a Lua thing, i.e. Lua assumes anything without `local` is global, but in Teal you have to specify?

**Comment by euclidianAce** [comment]
> It seems like global is a Teal thing, not a Lua thing, i.e. Lua assumes anything without local is global, but in Teal you have to specify?

Yes, exactly.

> my global foo = bar statements trigger unknown variable warnings. I can change it to global foo = bar to squelch the warning but I don't think that's valid Lua

Again correct. the `global` "keyword" (technically not a keyword, but gets special treatment in certain places) is Teal only

> It's a little annoying that when Teal typechecks my Lua code, my global foo = bar statements trigger unknown variable warnings

This is Teal saying that it doesn't know where these variables come from. A more "correct" way to silence these is to put more declarations in your `global_env_def` like:

```lua
-- env.d.tl
global foo: string
```
then you can use them in your Lua code without the warning
```lua
-- foo.lua
foo = "hello"
```
and should (hopefully) work
```
$ tl check --global-env-def env foo.lua
========================================
Type checked foo.lua
0 errors detected -- you can use:

   tl run foo.lua

       to run foo.lua as a program

   tl gen foo.lua

       to generate foo.out.lua
```

> A factor against me is that I'm fairly new to Lua in general

Not to seem dismissing, but I would definitely reccommend getting a little familiar with pure Lua for a little bit first. Teal is relatively young and the current documentation serves more as a "you know Lua but want types" rather than "you want to learn Teal as a standalone language" (again not to try and drive you away! always glad to have more people using teal :laughing:)

**Comment by tooolbox** [comment]
> This is Teal saying that it doesn't know where these variables come from. A more "correct" way to silence these is to put more declarations in your global_env_def

What if I'm declaring a global in my Lua file?  Can't Teal just infer the type for me?

I guess the safe stance is for Teal to assume you've typo'd an existing variable, and only by declaring it in `.d.tl` do you tell Teal, "yes, I'm declaring a global in this Lua file".  But still a little annoying.

> Not to seem dismissing, but I would definitely reccommend getting a little familiar with pure Lua for a little bit first. Teal is relatively young and the current documentation serves more as a "you know Lua but want types" rather than "you want to learn Teal as a standalone language" (again not to try and drive you away! always glad to have more people using teal)

Shrug.  It's not too crazy and the learning curve is worth the type safety.  For the most part the docs have been pretty darn good, this is I think the first time I've needed to ask anything.

**Comment by lenscas** [comment]
> What if I'm declaring a global in my Lua file? Can't Teal just infer the type for me?

No, teal right now doesn't do a lot of inferring and there are multiple ways in lua to edit the value of a global and for lua this means multiple ways to change the type as well.

**Comment by hishamhm** [comment]
> I guess the safe stance is for Teal to assume you've typo'd an existing variable, and only by declaring it in .d.tl do you tell Teal, "yes, I'm declaring a global in this Lua file". But still a little annoying.

Yes, we made that choice to be on the safe side. We hope that over time you'll agree with us that the overall profit of catching typos exceeds the amortized cost of the little annoyance. :)

> It's not too crazy and the learning curve is worth the type safety. For the most part the docs have been pretty darn good, this is I think the first time I've needed to ask anything.

This is encouraging feedback! :) 

I'm closing this one for now since the question seems to have been answered. Feel free to reopen if you feel otherwise, or open new issues if you hit into anything else! Thanks!!
