### ISSUE TITLE
Redefining methods doesn't result in error while redefining functions does

### ISSUE THREAD

**Issue by vulpivia** [teal-language/tl#496]
A method redefinition

```
local record Y
end

function Y:do_x(a: integer, b: integer): integer
    return a + b
end

function Y:do_x(a: integer): integer
    return self:do_x(a, 1)
end
```

checked by `tl check` doesn't report an error, while a function redefinition

```
function do_x(a: integer, b: integer): integer
    return a + b
end

function do_x(a: integer): integer
    return do_x(a, 1)
end
```

does report the error `wrong number of arguments (given 2, expects 1)`. I'm assuming the same behavior (reporting the error) would be correct even for a method redefinition?

**Comment by kikito** [comment]
I do agree that it will probably make sense to do the same thing in both cases.

However, a way to do monkeypatching in Lua is doing this redefinition pattern:

```
-- original definition:
function f(a)
  ... (do something with a)
end

-- monkeypatching:
local oldf = f
f = function(a, b)
  ... (do something else)
  oldf(a)
  ...
end
```

A similar one could be done in methods. I can't speak about how frequent this pattern will be (monkeypatching itself isn't that frequent after all) but it can happen. I am not sure about what the right solution is here. Is there a way to allow for this to happen in Teal? Maybe by forcing things with `as`?

**Comment by hishamhm** [comment]
I agree this behavior should change. I think it's a bug, because the definitions could be very incompatible, leading to runtime errors that would go unnoticed.

The reason why we have this bug is because record definitions _do_ allow for multiple declarations of a function field. This is to represent functions from Lua libraries that handle their arguments dynamically, so that we can give them a well-behaved Teal interface. For example, we can present this interface in Teal:

```lua
-- Teal code
record MyLuaLib
   func: function(string, integer)
   func: function(integer, boolean, boolean)
end
```

when a Lua library is actually implemented as 

```lua
-- plain Lua code
function MyLuaLib.func(a, b, c)
   if type(a) == "string" then
      -- ...code assuming b is an integer...
   else
      -- ...code assuming b and c are booleans...
   end
end
```

without having to resort to a type such as `func: function(string|integer, integer|boolean, boolean)`, which would incorrectly accept `func("x", true, true)`.

Teal itself is not complex enough to allow such polymorphic functions to be written in Teal, but they can come from Lua libs, so we allow multiple distinct entries inside `record` definitions. What I'm thinking is that we should disallow them in `function` definitions.
