### ISSUE TITLE
Error with custom (non-native) types in global variable declarations in .d.tl files

### ISSUE THREAD

**Issue by PinocchioStrings** [teal-language/tl#518]
```
-- somefile.d.tl:
local type Foobar = number -- Global or local same results, alias or record same results.
local MyLocalNumber: number -- Works
local MyLocalFoobar: Foobar -- Works
global MyGlobalNumber: number -- Works
global MyGlobalFoobar: Foobar -- Error: cannot redeclare global with a different type: previous type of MyGlobalFoobar is Foobar
-- Only generates the above error in .d.tl files, not in regular .tl files.
-- EDIT:
-- Despite the error, the declaration is still in effect for dependent .tl files (in my particular case this is a global_env_def).
-- The error won't show up when you run "tl build", but it shows up when you run "tl check somefile.d.tl"
-- It also shows up in vscode with the vscode-teal plugin, but again only for .d.tl files, not regular .tl files.
```

**Comment by hishamhm** [comment]
I'm unable to reproduce this on either the latest `master` or the latest release — I created the file `somefile.d.tl` with the above 5 lines, but `tl check somefile.d.tl` passes, it only produces warnings about the unused local variables, as expected.

**Comment by thefoodworksdotorg** [comment]
I did some further testing and it turns out that the problem only occurs when there is a tlconfig.lua or a command line option that specifies the same file as global_env_def.

I guess that makes sense, tl would probably be processing the same file twice as though they were a single file? Alas the problem is that it makes tl check (and the teal vscode plugin) worse than useless for the global_env_def file.

If this is the case, then the solution would be to prevent tl from using the global_env_def file when it is the same as the file currently being checked.

(Quite aside from that, I already disabled the teal plugin because it tendsto crash and generate error popups during normal use).

**Comment by hishamhm** [comment]
@PinocchioStrings Could you test this quick hack and see if it solves the issue for you?

```diff
diff --git a/tl b/tl
index 42a7832..d291884 100755
--- a/tl
+++ b/tl
@@ -135,7 +135,7 @@ local function setup_env(tlconfig, filename)
    local gen_target = tlconfig["gen_target"]
 
    tlconfig._init_env_modules = tlconfig._init_env_modules or {}
-   if tlconfig.global_env_def then
+   if tlconfig.global_env_def and tlconfig.global_env_def ~= filename then
       table.insert(tlconfig._init_env_modules, 1, tlconfig.global_env_def)
    end
 
```

This might not be smart enough — e.g. for detecting absolute versus relative pathnames — but it might prove sufficient. @euclidianAce: do you think Cyan suffers from a similar issue?

**Comment by hishamhm** [comment]
@makspll are you able to test the code tweak I suggested above and see if it addresses your issue?

**Comment by hishamhm** [comment]
Ah, that makes sense! I missed the misleading error message.
