### ISSUE TITLE
Missing separator argument for string.rep 

### ISSUE THREAD

**Issue by CoolingTool** [teal-language/tl#593]
https://www.lua.org/manual/5.4/manual.html#pdf-string.rep
![image](https://user-images.githubusercontent.com/62089272/207121436-8621538a-8484-4baa-baff-0de90f5f62ad.png)

as you can tell i don't know how to write issues

**Comment by icy-lava** [comment]
I see the problem is here: https://github.com/teal-language/tl/blob/e4639a40a414ce670b06ff724335b689ad4a4177/tl.tl#L5474

I could try and fix it, but the problem is that the third arg doesn't exist in lua 5.1 (it does exist in 5.2+ and luajit).

@hishamhm is there a way I could define it conditionally based on the version?

**Comment by hishamhm** [comment]
Compat-5.3 can provide the third argument, so it should be ok to enable it
unconditionally, triggering the compat glue code like we do for some other
functions.
