### ISSUE TITLE
spurious error when using the result of string.gsub

### ISSUE THREAD

**Issue by fperrad** [teal-language/tl#678]
```
$ cat gsub.tl 
global function translate (str: any)
     if type(str) == 'string' then
         -- type not narrowed, so there are error in 2 following lines
         str = str:gsub('a', 'A')
         str = str:gsub('b', 'B')
     end
     if str is string then
         -- type narrowed, so no error at the following line
         str = str:gsub('c', 'C')
         -- now spurious error at the following line, look likes the return of `gsub` is not a string
         str = str:gsub('d', 'D')
     end
     if type(str) == 'string' then
         -- type not narrowed, so there are error in 2 following lines
         str = string.gsub(str, 'e', 'E')
         str = string.gsub(str, 'f', 'F')
     end
     if str is string then
         -- type narrowed, so no error at the following line
         str = string.gsub(str, 'g', 'G')
         -- now spurious error at the following line, look likes the return of `gsub` is not a string
         str = string.gsub(str, 'h', 'H')
     end
end
$ tl gen --check gsub.tl 
Wrote: gsub.lua
========================================
6 errors:
gsub.tl:4:20: cannot index key 'gsub' in any 'str' of type <any type>
gsub.tl:5:20: cannot index key 'gsub' in any 'str' of type <any type>
gsub.tl:11:20: cannot index key 'gsub' in any 'str' of type <any type>
gsub.tl:15:28: argument 1: got <any type>, expected string
gsub.tl:16:28: argument 1: got <any type>, expected string
gsub.tl:22:28: argument 1: got <any type>, expected string
```

**Comment by hishamhm** [comment]
* `type()` does not narrow, that's expected (because it could be used it complex expressions with side-effects), that's why I added the more restricted `is` operator, which reliably has the shape `VAR is TYPE`
* The compiler does not do generalized implicit flow typing: it does not update the known type of a variable on each assignment (it's a statically-typed language, after all, not a type checker for a dynamically-typed one). There are a few situations where you get "explicit" flow typing, such as when using `if VAR is TYPE`: that narrows `str` from `any` to `string`. By assigning to `str`, however, you drop the narrowing and revert the variable back to the declared type, which is `any`. Performing generalized flow typing (that works across conditions, loops, function calls with side-effects, etc) would require a much more complex dataflow analysis than Teal's current single-pass compiler does.
* I have playing with extending flow typing to assignment results, but there were significant edge cases — for instance, I could make it work for the examples above, but it would then blow up in a slightly different example (especially as you add subtyping relationships).
* The `any` type is not a very useful or convenient one (`any` accepts anything, but other types don't accept `any`), and isn't really intended to give you the convenience of dynamically-typed programming. Your best bet for now is to check it with `is` (or hard-cast with `as` if you're sure of the type) and then assign to a local with the known type.
