### ISSUE TITLE
spurious error "cannot resolve a type" with union

### ISSUE THREAD

**Issue by fperrad** [teal-language/tl#695]
```
$ cat union.tl 
global function f1(val: string)
    if val is string then  -- warning: val (of type string) is always a string
        print(val)
    else
        error("string expected")
    end
end

global function f2(val: string|number)
    if val is string then
        print(val)
    elseif val is number then  -- warning: val (of type number (inferred at ...)) is always a number
        print(val)
    else  -- ERROR: cannot resolve a type for val here
        error("string or number expected")
    end
end
$ ./tl check union.tl
========================================
2 warnings:
union.tl:2:12: val (of type string) is always a string
union.tl:12:16: val (of type number (inferred at union.tl:12:5)) is always a number
========================================
1 error:
union.tl:14:5: cannot resolve a type for val here
```

**Comment by hishamhm** [comment]
The error is not spurious: if the type is `A|B`, and you have branches already covering cases for both `A` and `B`, the third branch is unreachable: there is no valid type inferrable for `var` in that branch.

**Comment by lenscas** [comment]
> The error is not spurious: if the type is `A|B`, and you have branches already covering cases for both `A` and `B`, the third branch is unreachable: there is no valid type inferrable for `var` in that branch.

considering that teal uses lua's `type` function to work with the `is` syntax, and that every value in teal can be `nil` regardless of type, shouldn't the type be `nil` in the else branch?

**Comment by hishamhm** [comment]
> considering that teal uses lua's type function to work with the is syntax, and that every value in teal can be nil regardless of type, shouldn't the type be nil in the else branch?

@lenscas fair point! I stand corrected.

**Comment by hishamhm** [comment]
> after adding a explicit nil in union, tl gives the same kind of error & warnings

Because `nil` is currently implied in every type, `X|nil` is currently equivalent(-ish?`*`) to `X`, so this result doesn't suprise me.

But I agree that the behavior you described in the issue needs changing, at the very least to make the behavior of `f1` and `f2` consistent, and ideally, to make the `else` block of `f2` infer `val` to `nil`.

(`*` I admit I don't have the precise semantics for that off the top of my head, which is a strong indicator that the current semantics are not ideal — I know, I know, we'll get rid of nil-everywhere eventually...)
