### ISSUE TITLE
[next branch] Total annotation asks for functions too

### ISSUE THREAD

**Issue by Andre-LA** [teal-language/tl#747]
```lua
local record A
	v: number
end

function A:echo()
	print('A:', self.v)
end

local b <total>: A = { v = 10 }
```

> output:
> test.tl:27:7: record variable declared <total> does not declare values for all fields (missing: echo)

Is this the expected behavior?

This also happens on Teal Playground, so I suppose this behavior it's also on current Teal.

**Comment by hishamhm** [comment]
Ahh, that's a tricky one. We could special-case function types, but in the case of fields that in a language C would be "function pointers", you'd _want_ those to be checked for totality in definition. And since metatables are added dynamically, giving special behavior for functions added using the `function A:echo` syntax feels like a bit of a stretch (though it might be the simplest immediate solution to this issue).

I sort of regret adding `<total>` to the record type because records are usually more mutable than maps-of-enums (which was the original intended use-case). It's really a poor substitute for non-nil fields...

**Comment by Andre-LA** [comment]
(edit: renamed `a` to `b`)

No worries,

I'm not too much familiar with PL or type theory so Idk if I'm missing something but as an user:

I think it makes sense to `<total>` to only check for what's inside the `record ... end` and not the functions outside it (not necessarily methods).

The reason for this is that the `echo` method it's a field on `A` table, not `b`, if I want this check though, I would add `echo: function(A)` on the record's fields instead.

**Comment by hishamhm** [comment]
@Andre-LA I implemented this in the `next` branch!

**Comment by hishamhm** [comment]
Thanks for the report and feedback! Closing this one

**Comment by Andre-LA** [comment]
Thanks!
