### ISSUE TITLE
unexpected propagation of <const> attribute

### ISSUE THREAD

**Issue by fperrad** [teal-language/tl#759]
```lua
local utf8 = utf8
if not utf8 then
   local ok, lutf8 = pcall(require, 'lua-utf8')
   if ok then
      utf8 = lutf8  -- Error: cannot assign to <const> variable
   end
end
```

The global `utf8` has the <const> attribute.
But the `local utf8` inherits of this attribute.

```
$ tl check const.tl 
========================================
2 errors:
const.tl:3:27: module not found: 'lua-utf8'
const.tl:5:7: cannot assign to <const> variable
```

**Comment by hishamhm** [comment]
@fperrad I fixed this in the `next` branch! It should now allow the pattern that you described. (See testcase in [181d2a5](https://github.com/teal-language/tl/commit/181d2a546798ccc10ae3e61383e86e0891921ec5)).

I haven't been backporting fixes to `master` because I'm really in the final stretch for the `next` branch (hoping to release Sep/Oct). Could you give `next` a try?

(Also, if you're using `--gen-compat` then utf8 compatibility should come for free via compat-5.3 — but IIRC you're not using it because of the bit operations? Is that the case?)

Thank you for the report!
