### ISSUE TITLE
Support forward declarations, at least in a record

### ISSUE THREAD

**Issue by mtdowling** [teal-language/tl#771]
In Teal today, I have to rearrange my code so that functions of a record that need to call other functions of a record are defined before they're called. Maybe the parser is implemented in a single pass and doesn't support patching references once a whole file is parsed. I think this limitation ends up making my code less readable: implementation details of a greater abstraction now have to come before the abstraction. I'd prefer rather to follow the "newspaper" approach where the main concept is written, and then each function it relies on follows.

An example of this right now is that I'm having to move the `new` method of a record to the end of a file because it needs to call other methods of the record. I'd much rather `new` appear first, followed by other methods. I understand this will complicate the parser, but I think this is worth it in the long run, so I wanted to track this feature request here.

```
function World.new(config: WorldConfig): World
    -- trimmed...
    for _, component in ipairs(config.components) do
        world:registerComponent(component)
        --    ^ error because I'm calling a function that hasn't been defined yet
    end
    return world
end

function World:registerComponent(component: any)
   --- trimmed
```

**Comment by hishamhm** [comment]
You can do forward declarations in a record, you just need to declare it as a field of a `function` type:

```lua
local record World
   registerComponent: function(World, any)
end
```

**Comment by mtdowling** [comment]
Ah right. I think that makes sense for interfaces once they land in the next version, but I it seems a little inconvenient for normal records since I have to write the same method signatures twice.

**Comment by hishamhm** [comment]
Yes, but writing signatures twice is pretty much the definition of a forward declaration, as seen in C and other languages.

And yes, Teal does implement a single-pass type checker at the moment -- back-patching dangling method references would make it considerably more difficult to perform flow-based type inference, since that would propagate dangling types for inferred variables as well. So, thank you for the feedback, which I'll keep in mind, but unfortunately, I have no short-term plans to change this.
