### ISSUE TITLE
 Transitivity of arity

### ISSUE THREAD

**Issue by fperrad** [teal-language/tl#820]
```lua
local function foo (val: string)
    val = val or "default"
    print(val)
end

foo()  -- wrong number of arguments (given 0, expects 1)
```

```lua
local function foo (val?: string)  -- `val` must be optional
    val = val or "default"
    print(val)
end

foo()  -- OK
```

Now, with 2 functions `foo` and `bar`

```lua
local function foo (val: string)
    val = val or "default"
    print(val)
end

local function bar (val: string)
    foo(val)
end

bar()  -- wrong number of arguments (given 0, expects 1)
```

```lua
local function foo (val: string)
    val = val or "default"
    print(val)
end

local function bar (val?: string)  -- `val` must be optional
    foo(val)  -- [[MY EXPECTATION IS HERE]] wrong number of arguments (given 0, expects 1)
end

bar()  -- OK
```

currently, there is no transitivity

with transitivity, `val` must be optional in both function

```lua
local function foo (val?: string)  -- `val` must be optional
    val = val or "default"
    print(val)
end

local function bar (val?: string)  -- `val` must be optional
    foo(val)  -- OK
end

bar()  -- OK
```

**Comment by hishamhm** [comment]
That is a known limitation of the current model. The arity check refers simply to the number of arguments passed, not their values or types. Just like you can call  `function foo(var: string)` with `foo(nil)`, you can call it with `foo(val)` where `val` may be nil. Those are 1-ary calls for a 1-ary function.

In contrast, in TypeScript you get the error where you expect because the `val?` annotation actually changes the type of the variable (in TS, `val?: string` means `string | undefined`, and `val: string?` means `string | null`).

I do not plan to change the arity check semantics to the behavior you described. I hope that in a future revision of the language we will get nil-strictness at last (I have some plans), so examples similar to yours will trigger an error, but when that happens those will be type errors and not arity errors.
