### ISSUE TITLE
unexpected or missing error with optional parameter

### ISSUE THREAD

**Issue by fperrad** [teal-language/tl#827]
here, errors are unexpected (prototype matches)
```lua
local fcts: {string:function(val: any, opt?: string)}

fcts['foo'] = function (val: string)
    print(val)
end

fcts['foo2'] = function (val: string, val2: string)  --  in assignment: incompatible number of arguments: got 2 (string, string), expected at least 1 and at most 2 (<any type>, string)
    print(val, val2)
end

fcts['bar'] = function (val: number)
    print(val)
end

fcts['bar2'] = function (val: number, val2: string)  -- in assignment: incompatible number of arguments: got 2 (number, string), expected at least 1 and at most 2 (<any type>, string)
    print(val, val2)
end
```
and conversely here, errors are missing
```lua
local fcts2: {string:function(val: any, val2: string)}

fcts2['foo'] = function (val: string)  -- [[EXPECTED ERROR]] in assignment: incompatible number of arguments: got 1 (string), expected 2 (<any type>, string)
    print(val)
end

fcts2['foo2'] = function (val: string, val2: string)
    print(val, val2)
end

fcts2['bar'] = function (val: number)  -- [[EXPECTED ERROR]] in assignment: incompatible number of arguments: got 1 (number), expected 2 (<any type>, string)
    print(val)
end

fcts2['bar2'] = function (val: number, val2: string)
    print(val, val2)
end
```

**Comment by hishamhm** [comment]
There are two opposing ways to look at this. 

One way is to look at it is the way you expected it to work.

The other way is to consider that

* in `fcts`, the array is declared to have an optional second argument, so that a caller can choose to do either `fcts[x](a)` or `fcts[x](a, b)` at will. Entries `foo2` and `bar2`, however, are declaring that in those functions the second argument is always needed, so the `fcts[x](a)` call won't match their intention.
* in `fcts2`, the array is declared to hold 2-ary functions, so that a caller can do something like `for _, f in ipairs(fcts2) do f(a, b) end` on all elements, but elements which don't need to use the second argument such as `foo` and `bar` are free to not declare it because they can be simply ignored.

I don't think one way is more correct than the other.

For `fcts2`, I ended up finding the second behavior more useful to me when using it in `tl.tl`. I think that was already the case in Teal 0.15.

For `fcts`, again, I think either interpretation is valid. Given that function matching is already bivariant (which is a more lax, and unsound, way of matching), I think there's a better case to claim that Teal should be less strict there and not error (that is, to act like you expected).

**Comment by hishamhm** [comment]
> A message like got 2 (number, string), expected at least 1 and at most 2 (<any type>, string) is very disturbing, because I don't see what I could do better.

That's good feedback, thanks -- that message was designed for  function calls and reused for function assignments. I see it only makes sense in the former case.
