### ISSUE TITLE
Variadic return type?

### ISSUE THREAD

**Issue by pdesaulniers** [teal-language/tl#85]
I'm confused. Is there some way to return `...` from a function in Teal?
```lua
local lume = record
    -- Pushes all the given values to the end of the table t and returns the pushed values. 
    push: function<`N>(t: {`N}, ...: `N): (...: `N) -- FIXME: '...' as a return type?
end
```

**Comment by hishamhm** [comment]
That's a great question!

The good news is that type system _does_ support it! I use it in things like:

https://github.com/teal-language/tl/blob/master/tl.tl#L3274

Looks like we don't have a syntax for it, though. Since we don't have named return types, I think we should use `type...` for that, as in:

```
push: function<`N>(t: {`N}, ...: `N): `N...
```

I'm going to try my hand at implementing this now! (And livestream it at https://twitch.tv/hishamhm while I'm at it :D )
