### ISSUE TITLE
method call doesn't work with maps

### ISSUE THREAD

**Issue by fperrad** [teal-language/tl#864]
```
local record Object
end

local type Fn = function(self: Object)
local type Alt = {string:Fn}

local obj: Object = {}
(obj as Alt).foo(obj)  -- OK
(obj as Alt):foo()     -- error: cannot index key 'foo' in type Alt
```

On plain Lua, `obj:foo()` is equivalent to `obj.foo(obj)`

**Comment by hishamhm** [comment]
This doesn't work either:

```lua
local record Object
end

local type Fn = function(self: Object)
local type Alt = {string:Fn}
local z: Alt
z:foo()
```

I think this behavior is reasonable.

> On plain Lua, obj:foo() is equivalent to obj.foo(obj)

That is not true in Teal. I chose not to make `:` a mere syntax sugar and keep the distinction between dot-indexing and colon-methods allows us to have better error messages when detecting mistakes between `.` and `:` usage, which is one of Lua's main footguns.

I think using `(obj as Alt).foo(obj)` in a situation like the above is the reasonable solution in Teal, because the value being indexed and the function argument do have different types: `(obj as Alt)` is `Alt`, and `obj` is `Object`. So, even if `:` was allowed in maps, you'd end up with a function argument of type `Alt`, which would be wrong.
