### ISSUE TITLE
Allow setting the working directory on the command-line?

### ISSUE THREAD

**Issue by pdesaulniers** [teal-language/tl#92]
Related: https://github.com/teal-language/vscode-teal/issues/9

I think it would be useful if `tl` allowed setting the working directory of the type-checker by passing a command-line argument.

Let's say we have a project with the following structure:
```
src/
  - main.tl
  - point.tl

tlconfig.lua
```

And `main.tl` looks like this:
```lua
local point = require("point")
```

Then, we could type-check `main.tl` by running the following command at the root of the project:
```
tl check --cwd=src/ src/main.tl
```
(Technically, we could even remove the `src/` prefix in `src/main.tl`, but that would mess up shell completion)

**Comment by hishamhm** [comment]
This effectively means adding the src/ directory to the require search path (which is doable today with environment variables TL_PATH or LUA_PATH).

Instead of just a rootdir flag, it would be useful to have a more general argument that adds (prepends?) dirs to the module search path, adjusting the package.path and package.cpath accordingly (we could guess the cpath library extension by looking at existing entries). Ideally this flag could be set multiple times and added to tlconfig.lua.
